# encoding: utf-8
# module PySide2.QtCore
# from D:\Maya2024\Python\lib\site-packages\PySide2\QtCore.cp310-win_amd64.pyd
# by generator 1.147
# no doc

# imports
import Shiboken as __Shiboken


class Qt(__Shiboken.Object):
    # no doc
    def bin(self, s): # real signature unknown; restored from __doc__
        """ bin(s: PySide2.QtCore.QTextStream) -> PySide2.QtCore.QTextStream """
        pass

    def bom(self, s): # real signature unknown; restored from __doc__
        """ bom(s: PySide2.QtCore.QTextStream) -> PySide2.QtCore.QTextStream """
        pass

    def center(self, s): # real signature unknown; restored from __doc__
        """ center(s: PySide2.QtCore.QTextStream) -> PySide2.QtCore.QTextStream """
        pass

    def dec(self, s): # real signature unknown; restored from __doc__
        """ dec(s: PySide2.QtCore.QTextStream) -> PySide2.QtCore.QTextStream """
        pass

    def endl(self, s): # real signature unknown; restored from __doc__
        """ endl(s: PySide2.QtCore.QTextStream) -> PySide2.QtCore.QTextStream """
        pass

    def fixed(self, s): # real signature unknown; restored from __doc__
        """ fixed(s: PySide2.QtCore.QTextStream) -> PySide2.QtCore.QTextStream """
        pass

    def flush(self, s): # real signature unknown; restored from __doc__
        """ flush(s: PySide2.QtCore.QTextStream) -> PySide2.QtCore.QTextStream """
        pass

    def forcepoint(self, s): # real signature unknown; restored from __doc__
        """ forcepoint(s: PySide2.QtCore.QTextStream) -> PySide2.QtCore.QTextStream """
        pass

    def forcesign(self, s): # real signature unknown; restored from __doc__
        """ forcesign(s: PySide2.QtCore.QTextStream) -> PySide2.QtCore.QTextStream """
        pass

    def hex(self, s): # real signature unknown; restored from __doc__
        """ hex(s: PySide2.QtCore.QTextStream) -> PySide2.QtCore.QTextStream """
        pass

    def left(self, s): # real signature unknown; restored from __doc__
        """ left(s: PySide2.QtCore.QTextStream) -> PySide2.QtCore.QTextStream """
        pass

    def lowercasebase(self, s): # real signature unknown; restored from __doc__
        """ lowercasebase(s: PySide2.QtCore.QTextStream) -> PySide2.QtCore.QTextStream """
        pass

    def lowercasedigits(self, s): # real signature unknown; restored from __doc__
        """ lowercasedigits(s: PySide2.QtCore.QTextStream) -> PySide2.QtCore.QTextStream """
        pass

    def noforcepoint(self, s): # real signature unknown; restored from __doc__
        """ noforcepoint(s: PySide2.QtCore.QTextStream) -> PySide2.QtCore.QTextStream """
        pass

    def noforcesign(self, s): # real signature unknown; restored from __doc__
        """ noforcesign(s: PySide2.QtCore.QTextStream) -> PySide2.QtCore.QTextStream """
        pass

    def noshowbase(self, s): # real signature unknown; restored from __doc__
        """ noshowbase(s: PySide2.QtCore.QTextStream) -> PySide2.QtCore.QTextStream """
        pass

    def oct(self, s): # real signature unknown; restored from __doc__
        """ oct(s: PySide2.QtCore.QTextStream) -> PySide2.QtCore.QTextStream """
        pass

    def reset(self, s): # real signature unknown; restored from __doc__
        """ reset(s: PySide2.QtCore.QTextStream) -> PySide2.QtCore.QTextStream """
        pass

    def right(self, s): # real signature unknown; restored from __doc__
        """ right(s: PySide2.QtCore.QTextStream) -> PySide2.QtCore.QTextStream """
        pass

    def scientific(self, s): # real signature unknown; restored from __doc__
        """ scientific(s: PySide2.QtCore.QTextStream) -> PySide2.QtCore.QTextStream """
        pass

    def showbase(self, s): # real signature unknown; restored from __doc__
        """ showbase(s: PySide2.QtCore.QTextStream) -> PySide2.QtCore.QTextStream """
        pass

    def uppercasebase(self, s): # real signature unknown; restored from __doc__
        """ uppercasebase(s: PySide2.QtCore.QTextStream) -> PySide2.QtCore.QTextStream """
        pass

    def uppercasedigits(self, s): # real signature unknown; restored from __doc__
        """ uppercasedigits(s: PySide2.QtCore.QTextStream) -> PySide2.QtCore.QTextStream """
        pass

    def ws(self, s): # real signature unknown; restored from __doc__
        """ ws(s: PySide2.QtCore.QTextStream) -> PySide2.QtCore.QTextStream """
        pass

    def __init__(self, *args, **kwargs): # real signature unknown
        pass

    @staticmethod # known case of __new__
    def __new__(*args, **kwargs): # real signature unknown
        """ Create and return a new object.  See help(type) for accurate signature. """
        pass

    AA_AttributeCount = PySide2.QtCore.Qt.ApplicationAttribute.AA_AttributeCount
    AA_CompressHighFrequencyEvents = PySide2.QtCore.Qt.ApplicationAttribute.AA_CompressHighFrequencyEvents
    AA_CompressTabletEvents = PySide2.QtCore.Qt.ApplicationAttribute.AA_CompressTabletEvents
    AA_DisableHighDpiScaling = PySide2.QtCore.Qt.ApplicationAttribute.AA_DisableHighDpiScaling
    AA_DisableNativeVirtualKeyboard = PySide2.QtCore.Qt.ApplicationAttribute.AA_DisableNativeVirtualKeyboard
    AA_DisableSessionManager = PySide2.QtCore.Qt.ApplicationAttribute.AA_DisableSessionManager
    AA_DisableShaderDiskCache = PySide2.QtCore.Qt.ApplicationAttribute.AA_DisableShaderDiskCache
    AA_DisableWindowContextHelpButton = PySide2.QtCore.Qt.ApplicationAttribute.AA_DisableWindowContextHelpButton
    AA_DontCheckOpenGLContextThreadAffinity = PySide2.QtCore.Qt.ApplicationAttribute.AA_DontCheckOpenGLContextThreadAffinity
    AA_DontCreateNativeWidgetSiblings = PySide2.QtCore.Qt.ApplicationAttribute.AA_DontCreateNativeWidgetSiblings
    AA_DontShowIconsInMenus = PySide2.QtCore.Qt.ApplicationAttribute.AA_DontShowIconsInMenus
    AA_DontShowShortcutsInContextMenus = PySide2.QtCore.Qt.ApplicationAttribute.AA_DontShowShortcutsInContextMenus
    AA_DontUseNativeDialogs = PySide2.QtCore.Qt.ApplicationAttribute.AA_DontUseNativeDialogs
    AA_DontUseNativeMenuBar = PySide2.QtCore.Qt.ApplicationAttribute.AA_DontUseNativeMenuBar
    AA_EnableHighDpiScaling = PySide2.QtCore.Qt.ApplicationAttribute.AA_EnableHighDpiScaling
    AA_ForceRasterWidgets = PySide2.QtCore.Qt.ApplicationAttribute.AA_ForceRasterWidgets
    AA_ImmediateWidgetCreation = PySide2.QtCore.Qt.ApplicationAttribute.AA_ImmediateWidgetCreation
    AA_MacDontSwapCtrlAndMeta = PySide2.QtCore.Qt.ApplicationAttribute.AA_MacDontSwapCtrlAndMeta
    AA_MacPluginApplication = PySide2.QtCore.Qt.ApplicationAttribute.AA_MacPluginApplication
    AA_MSWindowsUseDirect3DByDefault = PySide2.QtCore.Qt.ApplicationAttribute.AA_MSWindowsUseDirect3DByDefault
    AA_NativeWindows = PySide2.QtCore.Qt.ApplicationAttribute.AA_NativeWindows
    AA_PluginApplication = PySide2.QtCore.Qt.ApplicationAttribute.AA_PluginApplication
    AA_SetPalette = PySide2.QtCore.Qt.ApplicationAttribute.AA_SetPalette
    AA_ShareOpenGLContexts = PySide2.QtCore.Qt.ApplicationAttribute.AA_ShareOpenGLContexts
    AA_SynthesizeMouseForUnhandledTabletEvents = PySide2.QtCore.Qt.ApplicationAttribute.AA_SynthesizeMouseForUnhandledTabletEvents
    AA_SynthesizeMouseForUnhandledTouchEvents = PySide2.QtCore.Qt.ApplicationAttribute.AA_SynthesizeMouseForUnhandledTouchEvents
    AA_SynthesizeTouchForUnhandledMouseEvents = PySide2.QtCore.Qt.ApplicationAttribute.AA_SynthesizeTouchForUnhandledMouseEvents
    AA_Use96Dpi = PySide2.QtCore.Qt.ApplicationAttribute.AA_Use96Dpi
    AA_UseDesktopOpenGL = PySide2.QtCore.Qt.ApplicationAttribute.AA_UseDesktopOpenGL
    AA_UseHighDpiPixmaps = PySide2.QtCore.Qt.ApplicationAttribute.AA_UseHighDpiPixmaps
    AA_UseOpenGLES = PySide2.QtCore.Qt.ApplicationAttribute.AA_UseOpenGLES
    AA_UseSoftwareOpenGL = PySide2.QtCore.Qt.ApplicationAttribute.AA_UseSoftwareOpenGL
    AA_UseStyleSheetPropagationInWidgetStyles = PySide2.QtCore.Qt.ApplicationAttribute.AA_UseStyleSheetPropagationInWidgetStyles
    AA_X11InitThreads = PySide2.QtCore.Qt.ApplicationAttribute.AA_X11InitThreads
    AbsoluteSize = PySide2.QtCore.Qt.SizeMode.AbsoluteSize
    AccessibleDescriptionRole = PySide2.QtCore.Qt.ItemDataRole.AccessibleDescriptionRole
    AccessibleTextRole = PySide2.QtCore.Qt.ItemDataRole.AccessibleTextRole
    ActionMask = PySide2.QtCore.Qt.DropAction.ActionMask
    ActionsContextMenu = PySide2.QtCore.Qt.ContextMenuPolicy.ActionsContextMenu
    ActiveWindowFocusReason = PySide2.QtCore.Qt.FocusReason.ActiveWindowFocusReason
    AddToSelection = PySide2.QtCore.Qt.ItemSelectionOperation.AddToSelection
    AlignAbsolute = PySide2.QtCore.Qt.AlignmentFlag.AlignAbsolute
    AlignBaseline = PySide2.QtCore.Qt.AlignmentFlag.AlignBaseline
    AlignBottom = PySide2.QtCore.Qt.AlignmentFlag.AlignBottom
    AlignCenter = PySide2.QtCore.Qt.AlignmentFlag.AlignCenter
    AlignHCenter = PySide2.QtCore.Qt.AlignmentFlag.AlignHCenter
    AlignHorizontal_Mask = PySide2.QtCore.Qt.AlignmentFlag.AlignHorizontal_Mask
    AlignJustify = PySide2.QtCore.Qt.AlignmentFlag.AlignJustify
    AlignLeading = PySide2.QtCore.Qt.AlignmentFlag.AlignLeading
    AlignLeft = PySide2.QtCore.Qt.AlignmentFlag.AlignLeft
    Alignment = None # (!) real value is "<class 'PySide2.QtCore.Qt.Alignment'>"
    AlignmentFlag = None # (!) real value is "<class 'PySide2.QtCore.Qt.AlignmentFlag'>"
    AlignRight = PySide2.QtCore.Qt.AlignmentFlag.AlignRight
    AlignTop = PySide2.QtCore.Qt.AlignmentFlag.AlignTop
    AlignTrailing = PySide2.QtCore.Qt.AlignmentFlag.AlignTrailing
    AlignVCenter = PySide2.QtCore.Qt.AlignmentFlag.AlignVCenter
    AlignVertical_Mask = PySide2.QtCore.Qt.AlignmentFlag.AlignVertical_Mask
    AllButtons = PySide2.QtCore.Qt.MouseButton.AllButtons
    AllDockWidgetAreas = PySide2.QtCore.Qt.DockWidgetArea.AllDockWidgetAreas
    AllToolBarAreas = PySide2.QtCore.Qt.ToolBarArea.AllToolBarAreas
    AlphaDither_Mask = PySide2.QtCore.Qt.ImageConversionFlag.AlphaDither_Mask
    ALT = PySide2.QtCore.Qt.Modifier.ALT
    AltModifier = PySide2.QtCore.Qt.KeyboardModifier.AltModifier
    AnchorBottom = PySide2.QtCore.Qt.AnchorPoint.AnchorBottom
    AnchorHorizontalCenter = PySide2.QtCore.Qt.AnchorPoint.AnchorHorizontalCenter
    AnchorLeft = PySide2.QtCore.Qt.AnchorPoint.AnchorLeft
    AnchorPoint = None # (!) real value is "<class 'PySide2.QtCore.Qt.AnchorPoint'>"
    AnchorRight = PySide2.QtCore.Qt.AnchorPoint.AnchorRight
    AnchorTop = PySide2.QtCore.Qt.AnchorPoint.AnchorTop
    AnchorVerticalCenter = PySide2.QtCore.Qt.AnchorPoint.AnchorVerticalCenter
    ApplicationActive = PySide2.QtCore.Qt.ApplicationState.ApplicationActive
    ApplicationAttribute = None # (!) real value is "<class 'PySide2.QtCore.Qt.ApplicationAttribute'>"
    ApplicationHidden = PySide2.QtCore.Qt.ApplicationState.ApplicationHidden
    ApplicationInactive = PySide2.QtCore.Qt.ApplicationState.ApplicationInactive
    ApplicationModal = PySide2.QtCore.Qt.WindowModality.ApplicationModal
    ApplicationShortcut = PySide2.QtCore.Qt.ShortcutContext.ApplicationShortcut
    ApplicationState = None # (!) real value is "<class 'PySide2.QtCore.Qt.ApplicationState'>"
    ApplicationStates = None # (!) real value is "<class 'PySide2.QtCore.Qt.ApplicationStates'>"
    ApplicationSuspended = PySide2.QtCore.Qt.ApplicationState.ApplicationSuspended
    ArrowCursor = PySide2.QtCore.Qt.CursorShape.ArrowCursor
    ArrowType = None # (!) real value is "<class 'PySide2.QtCore.Qt.ArrowType'>"
    AscendingOrder = PySide2.QtCore.Qt.SortOrder.AscendingOrder
    AspectRatioMode = None # (!) real value is "<class 'PySide2.QtCore.Qt.AspectRatioMode'>"
    AutoColor = PySide2.QtCore.Qt.ImageConversionFlag.AutoColor
    AutoConnection = PySide2.QtCore.Qt.ConnectionType.AutoConnection
    AutoDither = PySide2.QtCore.Qt.ImageConversionFlag.AutoDither
    AutoText = PySide2.QtCore.Qt.TextFormat.AutoText
    AvoidDither = PySide2.QtCore.Qt.ImageConversionFlag.AvoidDither
    Axis = None # (!) real value is "<class 'PySide2.QtCore.Qt.Axis'>"
    BackButton = PySide2.QtCore.Qt.MouseButton.BackButton
    BackgroundColorRole = PySide2.QtCore.Qt.ItemDataRole.BackgroundColorRole
    BackgroundRole = PySide2.QtCore.Qt.ItemDataRole.BackgroundRole
    BacktabFocusReason = PySide2.QtCore.Qt.FocusReason.BacktabFocusReason
    BDiagPattern = PySide2.QtCore.Qt.BrushStyle.BDiagPattern
    BeginNativeGesture = PySide2.QtCore.Qt.NativeGestureType.BeginNativeGesture
    BevelJoin = PySide2.QtCore.Qt.PenJoinStyle.BevelJoin
    BGMode = None # (!) real value is "<class 'PySide2.QtCore.Qt.BGMode'>"
    BitmapCursor = PySide2.QtCore.Qt.CursorShape.BitmapCursor
    black = PySide2.QtCore.Qt.GlobalColor.black
    BlankCursor = PySide2.QtCore.Qt.CursorShape.BlankCursor
    BlockingQueuedConnection = PySide2.QtCore.Qt.ConnectionType.BlockingQueuedConnection
    blue = PySide2.QtCore.Qt.GlobalColor.blue
    BottomDockWidgetArea = PySide2.QtCore.Qt.DockWidgetArea.BottomDockWidgetArea
    BottomEdge = PySide2.QtCore.Qt.Edge.BottomEdge
    BottomLeftCorner = PySide2.QtCore.Qt.Corner.BottomLeftCorner
    BottomLeftSection = PySide2.QtCore.Qt.WindowFrameSection.BottomLeftSection
    BottomRightCorner = PySide2.QtCore.Qt.Corner.BottomRightCorner
    BottomRightSection = PySide2.QtCore.Qt.WindowFrameSection.BottomRightSection
    BottomSection = PySide2.QtCore.Qt.WindowFrameSection.BottomSection
    BottomToolBarArea = PySide2.QtCore.Qt.ToolBarArea.BottomToolBarArea
    BrushStyle = None # (!) real value is "<class 'PySide2.QtCore.Qt.BrushStyle'>"
    BusyCursor = PySide2.QtCore.Qt.CursorShape.BusyCursor
    BypassGraphicsProxyWidget = PySide2.QtCore.Qt.WindowType.BypassGraphicsProxyWidget
    BypassWindowManagerHint = PySide2.QtCore.Qt.WindowType.BypassWindowManagerHint
    CaseInsensitive = PySide2.QtCore.Qt.CaseSensitivity.CaseInsensitive
    CaseSensitive = PySide2.QtCore.Qt.CaseSensitivity.CaseSensitive
    CaseSensitivity = None # (!) real value is "<class 'PySide2.QtCore.Qt.CaseSensitivity'>"
    Checked = PySide2.QtCore.Qt.CheckState.Checked
    CheckState = None # (!) real value is "<class 'PySide2.QtCore.Qt.CheckState'>"
    CheckStateRole = PySide2.QtCore.Qt.ItemDataRole.CheckStateRole
    ChecksumIso3309 = PySide2.QtCore.Qt.ChecksumType.ChecksumIso3309
    ChecksumItuV41 = PySide2.QtCore.Qt.ChecksumType.ChecksumItuV41
    ChecksumType = None # (!) real value is "<class 'PySide2.QtCore.Qt.ChecksumType'>"
    ClickFocus = PySide2.QtCore.Qt.FocusPolicy.ClickFocus
    ClipOperation = None # (!) real value is "<class 'PySide2.QtCore.Qt.ClipOperation'>"
    ClosedHandCursor = PySide2.QtCore.Qt.CursorShape.ClosedHandCursor
    CoarseTimer = PySide2.QtCore.Qt.TimerType.CoarseTimer
    color0 = PySide2.QtCore.Qt.GlobalColor.color0
    color1 = PySide2.QtCore.Qt.GlobalColor.color1
    ColorMode_Mask = PySide2.QtCore.Qt.ImageConversionFlag.ColorMode_Mask
    ColorOnly = PySide2.QtCore.Qt.ImageConversionFlag.ColorOnly
    ConicalGradientPattern = PySide2.QtCore.Qt.BrushStyle.ConicalGradientPattern
    ConnectionType = None # (!) real value is "<class 'PySide2.QtCore.Qt.ConnectionType'>"
    ContainsItemBoundingRect = PySide2.QtCore.Qt.ItemSelectionMode.ContainsItemBoundingRect
    ContainsItemShape = PySide2.QtCore.Qt.ItemSelectionMode.ContainsItemShape
    ContextMenuPolicy = None # (!) real value is "<class 'PySide2.QtCore.Qt.ContextMenuPolicy'>"
    ControlModifier = PySide2.QtCore.Qt.KeyboardModifier.ControlModifier
    CoordinateSystem = None # (!) real value is "<class 'PySide2.QtCore.Qt.CoordinateSystem'>"
    CopyAction = PySide2.QtCore.Qt.DropAction.CopyAction
    Corner = None # (!) real value is "<class 'PySide2.QtCore.Qt.Corner'>"
    CoverWindow = PySide2.QtCore.Qt.WindowType.CoverWindow
    CrossCursor = PySide2.QtCore.Qt.CursorShape.CrossCursor
    CrossPattern = PySide2.QtCore.Qt.BrushStyle.CrossPattern
    CTRL = PySide2.QtCore.Qt.Modifier.CTRL
    CursorMoveStyle = None # (!) real value is "<class 'PySide2.QtCore.Qt.CursorMoveStyle'>"
    CursorShape = None # (!) real value is "<class 'PySide2.QtCore.Qt.CursorShape'>"
    CustomContextMenu = PySide2.QtCore.Qt.ContextMenuPolicy.CustomContextMenu
    CustomCursor = PySide2.QtCore.Qt.CursorShape.CustomCursor
    CustomDashLine = PySide2.QtCore.Qt.PenStyle.CustomDashLine
    CustomGesture = PySide2.QtCore.Qt.GestureType.CustomGesture
    CustomizeWindowHint = PySide2.QtCore.Qt.WindowType.CustomizeWindowHint
    cyan = PySide2.QtCore.Qt.GlobalColor.cyan
    darkBlue = PySide2.QtCore.Qt.GlobalColor.darkBlue
    darkCyan = PySide2.QtCore.Qt.GlobalColor.darkCyan
    darkGray = PySide2.QtCore.Qt.GlobalColor.darkGray
    darkGreen = PySide2.QtCore.Qt.GlobalColor.darkGreen
    darkMagenta = PySide2.QtCore.Qt.GlobalColor.darkMagenta
    darkRed = PySide2.QtCore.Qt.GlobalColor.darkRed
    darkYellow = PySide2.QtCore.Qt.GlobalColor.darkYellow
    DashDotDotLine = PySide2.QtCore.Qt.PenStyle.DashDotDotLine
    DashDotLine = PySide2.QtCore.Qt.PenStyle.DashDotLine
    DashLine = PySide2.QtCore.Qt.PenStyle.DashLine
    DateFormat = None # (!) real value is "<class 'PySide2.QtCore.Qt.DateFormat'>"
    DayOfWeek = None # (!) real value is "<class 'PySide2.QtCore.Qt.DayOfWeek'>"
    DecorationPropertyRole = PySide2.QtCore.Qt.ItemDataRole.DecorationPropertyRole
    DecorationRole = PySide2.QtCore.Qt.ItemDataRole.DecorationRole
    DefaultContextMenu = PySide2.QtCore.Qt.ContextMenuPolicy.DefaultContextMenu
    DefaultLocaleLongDate = PySide2.QtCore.Qt.DateFormat.DefaultLocaleLongDate
    DefaultLocaleShortDate = PySide2.QtCore.Qt.DateFormat.DefaultLocaleShortDate
    Dense1Pattern = PySide2.QtCore.Qt.BrushStyle.Dense1Pattern
    Dense2Pattern = PySide2.QtCore.Qt.BrushStyle.Dense2Pattern
    Dense3Pattern = PySide2.QtCore.Qt.BrushStyle.Dense3Pattern
    Dense4Pattern = PySide2.QtCore.Qt.BrushStyle.Dense4Pattern
    Dense5Pattern = PySide2.QtCore.Qt.BrushStyle.Dense5Pattern
    Dense6Pattern = PySide2.QtCore.Qt.BrushStyle.Dense6Pattern
    Dense7Pattern = PySide2.QtCore.Qt.BrushStyle.Dense7Pattern
    DescendingOrder = PySide2.QtCore.Qt.SortOrder.DescendingOrder
    Desktop = PySide2.QtCore.Qt.WindowType.Desktop
    DeviceCoordinates = PySide2.QtCore.Qt.CoordinateSystem.DeviceCoordinates
    DiagCrossPattern = PySide2.QtCore.Qt.BrushStyle.DiagCrossPattern
    Dialog = PySide2.QtCore.Qt.WindowType.Dialog
    DiffuseAlphaDither = PySide2.QtCore.Qt.ImageConversionFlag.DiffuseAlphaDither
    DiffuseDither = PySide2.QtCore.Qt.ImageConversionFlag.DiffuseDither
    DirectConnection = PySide2.QtCore.Qt.ConnectionType.DirectConnection
    DisplayPropertyRole = PySide2.QtCore.Qt.ItemDataRole.DisplayPropertyRole
    DisplayRole = PySide2.QtCore.Qt.ItemDataRole.DisplayRole
    DitherMode_Mask = PySide2.QtCore.Qt.ImageConversionFlag.DitherMode_Mask
    Dither_Mask = PySide2.QtCore.Qt.ImageConversionFlag.Dither_Mask
    DockWidgetArea = None # (!) real value is "<class 'PySide2.QtCore.Qt.DockWidgetArea'>"
    DockWidgetAreas = None # (!) real value is "<class 'PySide2.QtCore.Qt.DockWidgetAreas'>"
    DockWidgetAreaSizes = None # (!) real value is "<class 'PySide2.QtCore.Qt.DockWidgetAreaSizes'>"
    DockWidgetArea_Mask = PySide2.QtCore.Qt.DockWidgetArea.DockWidgetArea_Mask
    DontStartGestureOnChildren = PySide2.QtCore.Qt.GestureFlag.DontStartGestureOnChildren
    DotLine = PySide2.QtCore.Qt.PenStyle.DotLine
    DownArrow = PySide2.QtCore.Qt.ArrowType.DownArrow
    DragCopyCursor = PySide2.QtCore.Qt.CursorShape.DragCopyCursor
    DragLinkCursor = PySide2.QtCore.Qt.CursorShape.DragLinkCursor
    DragMoveCursor = PySide2.QtCore.Qt.CursorShape.DragMoveCursor
    Drawer = PySide2.QtCore.Qt.WindowType.Drawer
    DropAction = None # (!) real value is "<class 'PySide2.QtCore.Qt.DropAction'>"
    DropActions = None # (!) real value is "<class 'PySide2.QtCore.Qt.DropActions'>"
    Edge = None # (!) real value is "<class 'PySide2.QtCore.Qt.Edge'>"
    Edges = None # (!) real value is "<class 'PySide2.QtCore.Qt.Edges'>"
    EditRole = PySide2.QtCore.Qt.ItemDataRole.EditRole
    ElideLeft = PySide2.QtCore.Qt.TextElideMode.ElideLeft
    ElideMiddle = PySide2.QtCore.Qt.TextElideMode.ElideMiddle
    ElideNone = PySide2.QtCore.Qt.TextElideMode.ElideNone
    ElideRight = PySide2.QtCore.Qt.TextElideMode.ElideRight
    EndNativeGesture = PySide2.QtCore.Qt.NativeGestureType.EndNativeGesture
    EnterKeyDefault = PySide2.QtCore.Qt.EnterKeyType.EnterKeyDefault
    EnterKeyDone = PySide2.QtCore.Qt.EnterKeyType.EnterKeyDone
    EnterKeyGo = PySide2.QtCore.Qt.EnterKeyType.EnterKeyGo
    EnterKeyNext = PySide2.QtCore.Qt.EnterKeyType.EnterKeyNext
    EnterKeyPrevious = PySide2.QtCore.Qt.EnterKeyType.EnterKeyPrevious
    EnterKeyReturn = PySide2.QtCore.Qt.EnterKeyType.EnterKeyReturn
    EnterKeySearch = PySide2.QtCore.Qt.EnterKeyType.EnterKeySearch
    EnterKeySend = PySide2.QtCore.Qt.EnterKeyType.EnterKeySend
    EnterKeyType = None # (!) real value is "<class 'PySide2.QtCore.Qt.EnterKeyType'>"
    EventPriority = None # (!) real value is "<class 'PySide2.QtCore.Qt.EventPriority'>"
    ExactHit = PySide2.QtCore.Qt.HitTestAccuracy.ExactHit
    ExtraButton1 = PySide2.QtCore.Qt.MouseButton.ExtraButton1
    ExtraButton10 = PySide2.QtCore.Qt.MouseButton.ExtraButton10
    ExtraButton11 = PySide2.QtCore.Qt.MouseButton.ExtraButton11
    ExtraButton12 = PySide2.QtCore.Qt.MouseButton.ExtraButton12
    ExtraButton13 = PySide2.QtCore.Qt.MouseButton.ExtraButton13
    ExtraButton14 = PySide2.QtCore.Qt.MouseButton.ExtraButton14
    ExtraButton15 = PySide2.QtCore.Qt.MouseButton.ExtraButton15
    ExtraButton16 = PySide2.QtCore.Qt.MouseButton.ExtraButton16
    ExtraButton17 = PySide2.QtCore.Qt.MouseButton.ExtraButton17
    ExtraButton18 = PySide2.QtCore.Qt.MouseButton.ExtraButton18
    ExtraButton19 = PySide2.QtCore.Qt.MouseButton.ExtraButton19
    ExtraButton2 = PySide2.QtCore.Qt.MouseButton.ExtraButton2
    ExtraButton20 = PySide2.QtCore.Qt.MouseButton.ExtraButton20
    ExtraButton21 = PySide2.QtCore.Qt.MouseButton.ExtraButton21
    ExtraButton22 = PySide2.QtCore.Qt.MouseButton.ExtraButton22
    ExtraButton23 = PySide2.QtCore.Qt.MouseButton.ExtraButton23
    ExtraButton24 = PySide2.QtCore.Qt.MouseButton.ExtraButton24
    ExtraButton3 = PySide2.QtCore.Qt.MouseButton.ExtraButton3
    ExtraButton4 = PySide2.QtCore.Qt.MouseButton.ExtraButton4
    ExtraButton5 = PySide2.QtCore.Qt.MouseButton.ExtraButton5
    ExtraButton6 = PySide2.QtCore.Qt.MouseButton.ExtraButton6
    ExtraButton7 = PySide2.QtCore.Qt.MouseButton.ExtraButton7
    ExtraButton8 = PySide2.QtCore.Qt.MouseButton.ExtraButton8
    ExtraButton9 = PySide2.QtCore.Qt.MouseButton.ExtraButton9
    FastTransformation = PySide2.QtCore.Qt.TransformationMode.FastTransformation
    FDiagPattern = PySide2.QtCore.Qt.BrushStyle.FDiagPattern
    FillRule = None # (!) real value is "<class 'PySide2.QtCore.Qt.FillRule'>"
    FindChildOption = None # (!) real value is "<class 'PySide2.QtCore.Qt.FindChildOption'>"
    FindChildOptions = None # (!) real value is "<class 'PySide2.QtCore.Qt.FindChildOptions'>"
    FindChildrenRecursively = PySide2.QtCore.Qt.FindChildOption.FindChildrenRecursively
    FindDirectChildrenOnly = PySide2.QtCore.Qt.FindChildOption.FindDirectChildrenOnly
    FlatCap = PySide2.QtCore.Qt.PenCapStyle.FlatCap
    FocusPolicy = None # (!) real value is "<class 'PySide2.QtCore.Qt.FocusPolicy'>"
    FocusReason = None # (!) real value is "<class 'PySide2.QtCore.Qt.FocusReason'>"
    FontRole = PySide2.QtCore.Qt.ItemDataRole.FontRole
    ForbiddenCursor = PySide2.QtCore.Qt.CursorShape.ForbiddenCursor
    ForegroundRole = PySide2.QtCore.Qt.ItemDataRole.ForegroundRole
    ForeignWindow = PySide2.QtCore.Qt.WindowType.ForeignWindow
    ForwardButton = PySide2.QtCore.Qt.MouseButton.ForwardButton
    FramelessWindowHint = PySide2.QtCore.Qt.WindowType.FramelessWindowHint
    Friday = PySide2.QtCore.Qt.DayOfWeek.Friday
    FuzzyHit = PySide2.QtCore.Qt.HitTestAccuracy.FuzzyHit
    GestureCanceled = PySide2.QtCore.Qt.GestureState.GestureCanceled
    GestureFinished = PySide2.QtCore.Qt.GestureState.GestureFinished
    GestureFlag = None # (!) real value is "<class 'PySide2.QtCore.Qt.GestureFlag'>"
    GestureFlags = None # (!) real value is "<class 'PySide2.QtCore.Qt.GestureFlags'>"
    GestureStarted = PySide2.QtCore.Qt.GestureState.GestureStarted
    GestureState = None # (!) real value is "<class 'PySide2.QtCore.Qt.GestureState'>"
    GestureType = None # (!) real value is "<class 'PySide2.QtCore.Qt.GestureType'>"
    GestureUpdated = PySide2.QtCore.Qt.GestureState.GestureUpdated
    GlobalColor = None # (!) real value is "<class 'PySide2.QtCore.Qt.GlobalColor'>"
    gray = PySide2.QtCore.Qt.GlobalColor.gray
    green = PySide2.QtCore.Qt.GlobalColor.green
    GroupSwitchModifier = PySide2.QtCore.Qt.KeyboardModifier.GroupSwitchModifier
    HighDpiScaleFactorRoundingPolicy = None # (!) real value is "<class 'PySide2.QtCore.Qt.HighDpiScaleFactorRoundingPolicy'>"
    HighEventPriority = PySide2.QtCore.Qt.EventPriority.HighEventPriority
    HitTestAccuracy = None # (!) real value is "<class 'PySide2.QtCore.Qt.HitTestAccuracy'>"
    Horizontal = PySide2.QtCore.Qt.Orientation.Horizontal
    HorPattern = PySide2.QtCore.Qt.BrushStyle.HorPattern
    IBeamCursor = PySide2.QtCore.Qt.CursorShape.IBeamCursor
    IgnoreAction = PySide2.QtCore.Qt.DropAction.IgnoreAction
    IgnoreAspectRatio = PySide2.QtCore.Qt.AspectRatioMode.IgnoreAspectRatio
    IgnoredGesturesPropagateToParent = PySide2.QtCore.Qt.GestureFlag.IgnoredGesturesPropagateToParent
    ImAbsolutePosition = PySide2.QtCore.Qt.InputMethodQuery.ImAbsolutePosition
    ImageConversionFlag = None # (!) real value is "<class 'PySide2.QtCore.Qt.ImageConversionFlag'>"
    ImageConversionFlags = None # (!) real value is "<class 'PySide2.QtCore.Qt.ImageConversionFlags'>"
    ImAnchorPosition = PySide2.QtCore.Qt.InputMethodQuery.ImAnchorPosition
    ImAnchorRectangle = PySide2.QtCore.Qt.InputMethodQuery.ImAnchorRectangle
    ImCurrentSelection = PySide2.QtCore.Qt.InputMethodQuery.ImCurrentSelection
    ImCursorPosition = PySide2.QtCore.Qt.InputMethodQuery.ImCursorPosition
    ImCursorRectangle = PySide2.QtCore.Qt.InputMethodQuery.ImCursorRectangle
    ImEnabled = PySide2.QtCore.Qt.InputMethodQuery.ImEnabled
    ImEnterKeyType = PySide2.QtCore.Qt.InputMethodQuery.ImEnterKeyType
    ImFont = PySide2.QtCore.Qt.InputMethodQuery.ImFont
    ImhDate = PySide2.QtCore.Qt.InputMethodHint.ImhDate
    ImhDialableCharactersOnly = PySide2.QtCore.Qt.InputMethodHint.ImhDialableCharactersOnly
    ImhDigitsOnly = PySide2.QtCore.Qt.InputMethodHint.ImhDigitsOnly
    ImhEmailCharactersOnly = PySide2.QtCore.Qt.InputMethodHint.ImhEmailCharactersOnly
    ImhExclusiveInputMask = PySide2.QtCore.Qt.InputMethodHint.ImhExclusiveInputMask
    ImhFormattedNumbersOnly = PySide2.QtCore.Qt.InputMethodHint.ImhFormattedNumbersOnly
    ImhHiddenText = PySide2.QtCore.Qt.InputMethodHint.ImhHiddenText
    ImHints = PySide2.QtCore.Qt.InputMethodQuery.ImHints
    ImhLatinOnly = PySide2.QtCore.Qt.InputMethodHint.ImhLatinOnly
    ImhLowercaseOnly = PySide2.QtCore.Qt.InputMethodHint.ImhLowercaseOnly
    ImhMultiLine = PySide2.QtCore.Qt.InputMethodHint.ImhMultiLine
    ImhNoAutoUppercase = PySide2.QtCore.Qt.InputMethodHint.ImhNoAutoUppercase
    ImhNoEditMenu = PySide2.QtCore.Qt.InputMethodHint.ImhNoEditMenu
    ImhNone = PySide2.QtCore.Qt.InputMethodHint.ImhNone
    ImhNoPredictiveText = PySide2.QtCore.Qt.InputMethodHint.ImhNoPredictiveText
    ImhNoTextHandles = PySide2.QtCore.Qt.InputMethodHint.ImhNoTextHandles
    ImhPreferLatin = PySide2.QtCore.Qt.InputMethodHint.ImhPreferLatin
    ImhPreferLowercase = PySide2.QtCore.Qt.InputMethodHint.ImhPreferLowercase
    ImhPreferNumbers = PySide2.QtCore.Qt.InputMethodHint.ImhPreferNumbers
    ImhPreferUppercase = PySide2.QtCore.Qt.InputMethodHint.ImhPreferUppercase
    ImhSensitiveData = PySide2.QtCore.Qt.InputMethodHint.ImhSensitiveData
    ImhTime = PySide2.QtCore.Qt.InputMethodHint.ImhTime
    ImhUppercaseOnly = PySide2.QtCore.Qt.InputMethodHint.ImhUppercaseOnly
    ImhUrlCharactersOnly = PySide2.QtCore.Qt.InputMethodHint.ImhUrlCharactersOnly
    ImInputItemClipRectangle = PySide2.QtCore.Qt.InputMethodQuery.ImInputItemClipRectangle
    ImMaximumTextLength = PySide2.QtCore.Qt.InputMethodQuery.ImMaximumTextLength
    ImMicroFocus = PySide2.QtCore.Qt.InputMethodQuery.ImMicroFocus
    ImPlatformData = PySide2.QtCore.Qt.InputMethodQuery.ImPlatformData
    ImPreferredLanguage = PySide2.QtCore.Qt.InputMethodQuery.ImPreferredLanguage
    ImQueryAll = PySide2.QtCore.Qt.InputMethodQuery.ImQueryAll
    ImQueryInput = PySide2.QtCore.Qt.InputMethodQuery.ImQueryInput
    ImSurroundingText = PySide2.QtCore.Qt.InputMethodQuery.ImSurroundingText
    ImTextAfterCursor = PySide2.QtCore.Qt.InputMethodQuery.ImTextAfterCursor
    ImTextBeforeCursor = PySide2.QtCore.Qt.InputMethodQuery.ImTextBeforeCursor
    InitialSortOrderRole = PySide2.QtCore.Qt.ItemDataRole.InitialSortOrderRole
    InputMethodHint = None # (!) real value is "<class 'PySide2.QtCore.Qt.InputMethodHint'>"
    InputMethodHints = None # (!) real value is "<class 'PySide2.QtCore.Qt.InputMethodHints'>"
    InputMethodQueries = None # (!) real value is "<class 'PySide2.QtCore.Qt.InputMethodQueries'>"
    InputMethodQuery = None # (!) real value is "<class 'PySide2.QtCore.Qt.InputMethodQuery'>"
    IntersectClip = PySide2.QtCore.Qt.ClipOperation.IntersectClip
    IntersectsItemBoundingRect = PySide2.QtCore.Qt.ItemSelectionMode.IntersectsItemBoundingRect
    IntersectsItemShape = PySide2.QtCore.Qt.ItemSelectionMode.IntersectsItemShape
    InvertedLandscapeOrientation = PySide2.QtCore.Qt.ScreenOrientation.InvertedLandscapeOrientation
    InvertedPortraitOrientation = PySide2.QtCore.Qt.ScreenOrientation.InvertedPortraitOrientation
    ISODate = PySide2.QtCore.Qt.DateFormat.ISODate
    ISODateWithMs = PySide2.QtCore.Qt.DateFormat.ISODateWithMs
    ItemDataRole = None # (!) real value is "<class 'PySide2.QtCore.Qt.ItemDataRole'>"
    ItemFlag = None # (!) real value is "<class 'PySide2.QtCore.Qt.ItemFlag'>"
    ItemFlags = None # (!) real value is "<class 'PySide2.QtCore.Qt.ItemFlags'>"
    ItemIsAutoTristate = PySide2.QtCore.Qt.ItemFlag.ItemIsAutoTristate
    ItemIsDragEnabled = PySide2.QtCore.Qt.ItemFlag.ItemIsDragEnabled
    ItemIsDropEnabled = PySide2.QtCore.Qt.ItemFlag.ItemIsDropEnabled
    ItemIsEditable = PySide2.QtCore.Qt.ItemFlag.ItemIsEditable
    ItemIsEnabled = PySide2.QtCore.Qt.ItemFlag.ItemIsEnabled
    ItemIsSelectable = PySide2.QtCore.Qt.ItemFlag.ItemIsSelectable
    ItemIsTristate = PySide2.QtCore.Qt.ItemFlag.ItemIsTristate
    ItemIsUserCheckable = PySide2.QtCore.Qt.ItemFlag.ItemIsUserCheckable
    ItemIsUserTristate = PySide2.QtCore.Qt.ItemFlag.ItemIsUserTristate
    ItemNeverHasChildren = PySide2.QtCore.Qt.ItemFlag.ItemNeverHasChildren
    ItemSelectionMode = None # (!) real value is "<class 'PySide2.QtCore.Qt.ItemSelectionMode'>"
    ItemSelectionOperation = None # (!) real value is "<class 'PySide2.QtCore.Qt.ItemSelectionOperation'>"
    KeepAspectRatio = PySide2.QtCore.Qt.AspectRatioMode.KeepAspectRatio
    KeepAspectRatioByExpanding = PySide2.QtCore.Qt.AspectRatioMode.KeepAspectRatioByExpanding
    KeepEmptyParts = PySide2.QtCore.Qt.SplitBehaviorFlags.KeepEmptyParts
    Key = None # (!) real value is "<class 'PySide2.QtCore.Qt.Key'>"
    KeyboardModifier = None # (!) real value is "<class 'PySide2.QtCore.Qt.KeyboardModifier'>"
    KeyboardModifierMask = PySide2.QtCore.Qt.KeyboardModifier.KeyboardModifierMask
    KeyboardModifiers = None # (!) real value is "<class 'PySide2.QtCore.Qt.KeyboardModifiers'>"
    KeypadModifier = PySide2.QtCore.Qt.KeyboardModifier.KeypadModifier
    Key_0 = PySide2.QtCore.Qt.Key.Key_0
    Key_1 = PySide2.QtCore.Qt.Key.Key_1
    Key_2 = PySide2.QtCore.Qt.Key.Key_2
    Key_3 = PySide2.QtCore.Qt.Key.Key_3
    Key_4 = PySide2.QtCore.Qt.Key.Key_4
    Key_5 = PySide2.QtCore.Qt.Key.Key_5
    Key_6 = PySide2.QtCore.Qt.Key.Key_6
    Key_7 = PySide2.QtCore.Qt.Key.Key_7
    Key_8 = PySide2.QtCore.Qt.Key.Key_8
    Key_9 = PySide2.QtCore.Qt.Key.Key_9
    Key_A = PySide2.QtCore.Qt.Key.Key_A
    Key_Aacute = PySide2.QtCore.Qt.Key.Key_Aacute
    Key_Acircumflex = PySide2.QtCore.Qt.Key.Key_Acircumflex
    Key_acute = PySide2.QtCore.Qt.Key.Key_acute
    Key_AddFavorite = PySide2.QtCore.Qt.Key.Key_AddFavorite
    Key_Adiaeresis = PySide2.QtCore.Qt.Key.Key_Adiaeresis
    Key_AE = PySide2.QtCore.Qt.Key.Key_AE
    Key_Agrave = PySide2.QtCore.Qt.Key.Key_Agrave
    Key_Alt = PySide2.QtCore.Qt.Key.Key_Alt
    Key_AltGr = PySide2.QtCore.Qt.Key.Key_AltGr
    Key_Ampersand = PySide2.QtCore.Qt.Key.Key_Ampersand
    Key_Any = PySide2.QtCore.Qt.Key.Key_Any
    Key_Apostrophe = PySide2.QtCore.Qt.Key.Key_Apostrophe
    Key_ApplicationLeft = PySide2.QtCore.Qt.Key.Key_ApplicationLeft
    Key_ApplicationRight = PySide2.QtCore.Qt.Key.Key_ApplicationRight
    Key_Aring = PySide2.QtCore.Qt.Key.Key_Aring
    Key_AsciiCircum = PySide2.QtCore.Qt.Key.Key_AsciiCircum
    Key_AsciiTilde = PySide2.QtCore.Qt.Key.Key_AsciiTilde
    Key_Asterisk = PySide2.QtCore.Qt.Key.Key_Asterisk
    Key_At = PySide2.QtCore.Qt.Key.Key_At
    Key_Atilde = PySide2.QtCore.Qt.Key.Key_Atilde
    Key_AudioCycleTrack = PySide2.QtCore.Qt.Key.Key_AudioCycleTrack
    Key_AudioForward = PySide2.QtCore.Qt.Key.Key_AudioForward
    Key_AudioRandomPlay = PySide2.QtCore.Qt.Key.Key_AudioRandomPlay
    Key_AudioRepeat = PySide2.QtCore.Qt.Key.Key_AudioRepeat
    Key_AudioRewind = PySide2.QtCore.Qt.Key.Key_AudioRewind
    Key_Away = PySide2.QtCore.Qt.Key.Key_Away
    Key_B = PySide2.QtCore.Qt.Key.Key_B
    Key_Back = PySide2.QtCore.Qt.Key.Key_Back
    Key_BackForward = PySide2.QtCore.Qt.Key.Key_BackForward
    Key_Backslash = PySide2.QtCore.Qt.Key.Key_Backslash
    Key_Backspace = PySide2.QtCore.Qt.Key.Key_Backspace
    Key_Backtab = PySide2.QtCore.Qt.Key.Key_Backtab
    Key_Bar = PySide2.QtCore.Qt.Key.Key_Bar
    Key_BassBoost = PySide2.QtCore.Qt.Key.Key_BassBoost
    Key_BassDown = PySide2.QtCore.Qt.Key.Key_BassDown
    Key_BassUp = PySide2.QtCore.Qt.Key.Key_BassUp
    Key_Battery = PySide2.QtCore.Qt.Key.Key_Battery
    Key_Blue = PySide2.QtCore.Qt.Key.Key_Blue
    Key_Bluetooth = PySide2.QtCore.Qt.Key.Key_Bluetooth
    Key_Book = PySide2.QtCore.Qt.Key.Key_Book
    Key_BraceLeft = PySide2.QtCore.Qt.Key.Key_BraceLeft
    Key_BraceRight = PySide2.QtCore.Qt.Key.Key_BraceRight
    Key_BracketLeft = PySide2.QtCore.Qt.Key.Key_BracketLeft
    Key_BracketRight = PySide2.QtCore.Qt.Key.Key_BracketRight
    Key_BrightnessAdjust = PySide2.QtCore.Qt.Key.Key_BrightnessAdjust
    Key_brokenbar = PySide2.QtCore.Qt.Key.Key_brokenbar
    Key_C = PySide2.QtCore.Qt.Key.Key_C
    Key_Calculator = PySide2.QtCore.Qt.Key.Key_Calculator
    Key_Calendar = PySide2.QtCore.Qt.Key.Key_Calendar
    Key_Call = PySide2.QtCore.Qt.Key.Key_Call
    Key_Camera = PySide2.QtCore.Qt.Key.Key_Camera
    Key_CameraFocus = PySide2.QtCore.Qt.Key.Key_CameraFocus
    Key_Cancel = PySide2.QtCore.Qt.Key.Key_Cancel
    Key_CapsLock = PySide2.QtCore.Qt.Key.Key_CapsLock
    Key_Ccedilla = PySide2.QtCore.Qt.Key.Key_Ccedilla
    Key_CD = PySide2.QtCore.Qt.Key.Key_CD
    Key_cedilla = PySide2.QtCore.Qt.Key.Key_cedilla
    Key_cent = PySide2.QtCore.Qt.Key.Key_cent
    Key_ChannelDown = PySide2.QtCore.Qt.Key.Key_ChannelDown
    Key_ChannelUp = PySide2.QtCore.Qt.Key.Key_ChannelUp
    Key_Clear = PySide2.QtCore.Qt.Key.Key_Clear
    Key_ClearGrab = PySide2.QtCore.Qt.Key.Key_ClearGrab
    Key_Close = PySide2.QtCore.Qt.Key.Key_Close
    Key_Codeinput = PySide2.QtCore.Qt.Key.Key_Codeinput
    Key_Colon = PySide2.QtCore.Qt.Key.Key_Colon
    Key_Comma = PySide2.QtCore.Qt.Key.Key_Comma
    Key_Community = PySide2.QtCore.Qt.Key.Key_Community
    Key_Context1 = PySide2.QtCore.Qt.Key.Key_Context1
    Key_Context2 = PySide2.QtCore.Qt.Key.Key_Context2
    Key_Context3 = PySide2.QtCore.Qt.Key.Key_Context3
    Key_Context4 = PySide2.QtCore.Qt.Key.Key_Context4
    Key_ContrastAdjust = PySide2.QtCore.Qt.Key.Key_ContrastAdjust
    Key_Control = PySide2.QtCore.Qt.Key.Key_Control
    Key_Copy = PySide2.QtCore.Qt.Key.Key_Copy
    Key_copyright = PySide2.QtCore.Qt.Key.Key_copyright
    Key_currency = PySide2.QtCore.Qt.Key.Key_currency
    Key_Cut = PySide2.QtCore.Qt.Key.Key_Cut
    Key_D = PySide2.QtCore.Qt.Key.Key_D
    Key_Dead_a = PySide2.QtCore.Qt.Key.Key_Dead_a
    Key_Dead_A = PySide2.QtCore.Qt.Key.Key_Dead_A
    Key_Dead_Abovecomma = PySide2.QtCore.Qt.Key.Key_Dead_Abovecomma
    Key_Dead_Abovedot = PySide2.QtCore.Qt.Key.Key_Dead_Abovedot
    Key_Dead_Abovereversedcomma = PySide2.QtCore.Qt.Key.Key_Dead_Abovereversedcomma
    Key_Dead_Abovering = PySide2.QtCore.Qt.Key.Key_Dead_Abovering
    Key_Dead_Aboveverticalline = PySide2.QtCore.Qt.Key.Key_Dead_Aboveverticalline
    Key_Dead_Acute = PySide2.QtCore.Qt.Key.Key_Dead_Acute
    Key_Dead_Belowbreve = PySide2.QtCore.Qt.Key.Key_Dead_Belowbreve
    Key_Dead_Belowcircumflex = PySide2.QtCore.Qt.Key.Key_Dead_Belowcircumflex
    Key_Dead_Belowcomma = PySide2.QtCore.Qt.Key.Key_Dead_Belowcomma
    Key_Dead_Belowdiaeresis = PySide2.QtCore.Qt.Key.Key_Dead_Belowdiaeresis
    Key_Dead_Belowdot = PySide2.QtCore.Qt.Key.Key_Dead_Belowdot
    Key_Dead_Belowmacron = PySide2.QtCore.Qt.Key.Key_Dead_Belowmacron
    Key_Dead_Belowring = PySide2.QtCore.Qt.Key.Key_Dead_Belowring
    Key_Dead_Belowtilde = PySide2.QtCore.Qt.Key.Key_Dead_Belowtilde
    Key_Dead_Belowverticalline = PySide2.QtCore.Qt.Key.Key_Dead_Belowverticalline
    Key_Dead_Breve = PySide2.QtCore.Qt.Key.Key_Dead_Breve
    Key_Dead_Capital_Schwa = PySide2.QtCore.Qt.Key.Key_Dead_Capital_Schwa
    Key_Dead_Caron = PySide2.QtCore.Qt.Key.Key_Dead_Caron
    Key_Dead_Cedilla = PySide2.QtCore.Qt.Key.Key_Dead_Cedilla
    Key_Dead_Circumflex = PySide2.QtCore.Qt.Key.Key_Dead_Circumflex
    Key_Dead_Currency = PySide2.QtCore.Qt.Key.Key_Dead_Currency
    Key_Dead_Diaeresis = PySide2.QtCore.Qt.Key.Key_Dead_Diaeresis
    Key_Dead_Doubleacute = PySide2.QtCore.Qt.Key.Key_Dead_Doubleacute
    Key_Dead_Doublegrave = PySide2.QtCore.Qt.Key.Key_Dead_Doublegrave
    Key_Dead_e = PySide2.QtCore.Qt.Key.Key_Dead_e
    Key_Dead_E = PySide2.QtCore.Qt.Key.Key_Dead_E
    Key_Dead_Grave = PySide2.QtCore.Qt.Key.Key_Dead_Grave
    Key_Dead_Greek = PySide2.QtCore.Qt.Key.Key_Dead_Greek
    Key_Dead_Hook = PySide2.QtCore.Qt.Key.Key_Dead_Hook
    Key_Dead_Horn = PySide2.QtCore.Qt.Key.Key_Dead_Horn
    Key_Dead_i = PySide2.QtCore.Qt.Key.Key_Dead_i
    Key_Dead_I = PySide2.QtCore.Qt.Key.Key_Dead_I
    Key_Dead_Invertedbreve = PySide2.QtCore.Qt.Key.Key_Dead_Invertedbreve
    Key_Dead_Iota = PySide2.QtCore.Qt.Key.Key_Dead_Iota
    Key_Dead_Longsolidusoverlay = PySide2.QtCore.Qt.Key.Key_Dead_Longsolidusoverlay
    Key_Dead_Lowline = PySide2.QtCore.Qt.Key.Key_Dead_Lowline
    Key_Dead_Macron = PySide2.QtCore.Qt.Key.Key_Dead_Macron
    Key_Dead_o = PySide2.QtCore.Qt.Key.Key_Dead_o
    Key_Dead_O = PySide2.QtCore.Qt.Key.Key_Dead_O
    Key_Dead_Ogonek = PySide2.QtCore.Qt.Key.Key_Dead_Ogonek
    Key_Dead_Semivoiced_Sound = PySide2.QtCore.Qt.Key.Key_Dead_Semivoiced_Sound
    Key_Dead_Small_Schwa = PySide2.QtCore.Qt.Key.Key_Dead_Small_Schwa
    Key_Dead_Stroke = PySide2.QtCore.Qt.Key.Key_Dead_Stroke
    Key_Dead_Tilde = PySide2.QtCore.Qt.Key.Key_Dead_Tilde
    Key_Dead_u = PySide2.QtCore.Qt.Key.Key_Dead_u
    Key_Dead_U = PySide2.QtCore.Qt.Key.Key_Dead_U
    Key_Dead_Voiced_Sound = PySide2.QtCore.Qt.Key.Key_Dead_Voiced_Sound
    Key_degree = PySide2.QtCore.Qt.Key.Key_degree
    Key_Delete = PySide2.QtCore.Qt.Key.Key_Delete
    Key_diaeresis = PySide2.QtCore.Qt.Key.Key_diaeresis
    Key_Direction_L = PySide2.QtCore.Qt.Key.Key_Direction_L
    Key_Direction_R = PySide2.QtCore.Qt.Key.Key_Direction_R
    Key_Display = PySide2.QtCore.Qt.Key.Key_Display
    Key_division = PySide2.QtCore.Qt.Key.Key_division
    Key_Documents = PySide2.QtCore.Qt.Key.Key_Documents
    Key_Dollar = PySide2.QtCore.Qt.Key.Key_Dollar
    Key_DOS = PySide2.QtCore.Qt.Key.Key_DOS
    Key_Down = PySide2.QtCore.Qt.Key.Key_Down
    Key_E = PySide2.QtCore.Qt.Key.Key_E
    Key_Eacute = PySide2.QtCore.Qt.Key.Key_Eacute
    Key_Ecircumflex = PySide2.QtCore.Qt.Key.Key_Ecircumflex
    Key_Ediaeresis = PySide2.QtCore.Qt.Key.Key_Ediaeresis
    Key_Egrave = PySide2.QtCore.Qt.Key.Key_Egrave
    Key_Eisu_Shift = PySide2.QtCore.Qt.Key.Key_Eisu_Shift
    Key_Eisu_toggle = PySide2.QtCore.Qt.Key.Key_Eisu_toggle
    Key_Eject = PySide2.QtCore.Qt.Key.Key_Eject
    Key_End = PySide2.QtCore.Qt.Key.Key_End
    Key_Enter = PySide2.QtCore.Qt.Key.Key_Enter
    Key_Equal = PySide2.QtCore.Qt.Key.Key_Equal
    Key_Escape = PySide2.QtCore.Qt.Key.Key_Escape
    Key_ETH = PySide2.QtCore.Qt.Key.Key_ETH
    Key_Excel = PySide2.QtCore.Qt.Key.Key_Excel
    Key_Exclam = PySide2.QtCore.Qt.Key.Key_Exclam
    Key_exclamdown = PySide2.QtCore.Qt.Key.Key_exclamdown
    Key_Execute = PySide2.QtCore.Qt.Key.Key_Execute
    Key_Exit = PySide2.QtCore.Qt.Key.Key_Exit
    Key_Explorer = PySide2.QtCore.Qt.Key.Key_Explorer
    Key_F = PySide2.QtCore.Qt.Key.Key_F
    Key_F1 = PySide2.QtCore.Qt.Key.Key_F1
    Key_F10 = PySide2.QtCore.Qt.Key.Key_F10
    Key_F11 = PySide2.QtCore.Qt.Key.Key_F11
    Key_F12 = PySide2.QtCore.Qt.Key.Key_F12
    Key_F13 = PySide2.QtCore.Qt.Key.Key_F13
    Key_F14 = PySide2.QtCore.Qt.Key.Key_F14
    Key_F15 = PySide2.QtCore.Qt.Key.Key_F15
    Key_F16 = PySide2.QtCore.Qt.Key.Key_F16
    Key_F17 = PySide2.QtCore.Qt.Key.Key_F17
    Key_F18 = PySide2.QtCore.Qt.Key.Key_F18
    Key_F19 = PySide2.QtCore.Qt.Key.Key_F19
    Key_F2 = PySide2.QtCore.Qt.Key.Key_F2
    Key_F20 = PySide2.QtCore.Qt.Key.Key_F20
    Key_F21 = PySide2.QtCore.Qt.Key.Key_F21
    Key_F22 = PySide2.QtCore.Qt.Key.Key_F22
    Key_F23 = PySide2.QtCore.Qt.Key.Key_F23
    Key_F24 = PySide2.QtCore.Qt.Key.Key_F24
    Key_F25 = PySide2.QtCore.Qt.Key.Key_F25
    Key_F26 = PySide2.QtCore.Qt.Key.Key_F26
    Key_F27 = PySide2.QtCore.Qt.Key.Key_F27
    Key_F28 = PySide2.QtCore.Qt.Key.Key_F28
    Key_F29 = PySide2.QtCore.Qt.Key.Key_F29
    Key_F3 = PySide2.QtCore.Qt.Key.Key_F3
    Key_F30 = PySide2.QtCore.Qt.Key.Key_F30
    Key_F31 = PySide2.QtCore.Qt.Key.Key_F31
    Key_F32 = PySide2.QtCore.Qt.Key.Key_F32
    Key_F33 = PySide2.QtCore.Qt.Key.Key_F33
    Key_F34 = PySide2.QtCore.Qt.Key.Key_F34
    Key_F35 = PySide2.QtCore.Qt.Key.Key_F35
    Key_F4 = PySide2.QtCore.Qt.Key.Key_F4
    Key_F5 = PySide2.QtCore.Qt.Key.Key_F5
    Key_F6 = PySide2.QtCore.Qt.Key.Key_F6
    Key_F7 = PySide2.QtCore.Qt.Key.Key_F7
    Key_F8 = PySide2.QtCore.Qt.Key.Key_F8
    Key_F9 = PySide2.QtCore.Qt.Key.Key_F9
    Key_Favorites = PySide2.QtCore.Qt.Key.Key_Favorites
    Key_Finance = PySide2.QtCore.Qt.Key.Key_Finance
    Key_Find = PySide2.QtCore.Qt.Key.Key_Find
    Key_Flip = PySide2.QtCore.Qt.Key.Key_Flip
    Key_Forward = PySide2.QtCore.Qt.Key.Key_Forward
    Key_G = PySide2.QtCore.Qt.Key.Key_G
    Key_Game = PySide2.QtCore.Qt.Key.Key_Game
    Key_Go = PySide2.QtCore.Qt.Key.Key_Go
    Key_Greater = PySide2.QtCore.Qt.Key.Key_Greater
    Key_Green = PySide2.QtCore.Qt.Key.Key_Green
    Key_Guide = PySide2.QtCore.Qt.Key.Key_Guide
    Key_guillemotleft = PySide2.QtCore.Qt.Key.Key_guillemotleft
    Key_guillemotright = PySide2.QtCore.Qt.Key.Key_guillemotright
    Key_H = PySide2.QtCore.Qt.Key.Key_H
    Key_Hangul = PySide2.QtCore.Qt.Key.Key_Hangul
    Key_Hangul_Banja = PySide2.QtCore.Qt.Key.Key_Hangul_Banja
    Key_Hangul_End = PySide2.QtCore.Qt.Key.Key_Hangul_End
    Key_Hangul_Hanja = PySide2.QtCore.Qt.Key.Key_Hangul_Hanja
    Key_Hangul_Jamo = PySide2.QtCore.Qt.Key.Key_Hangul_Jamo
    Key_Hangul_Jeonja = PySide2.QtCore.Qt.Key.Key_Hangul_Jeonja
    Key_Hangul_PostHanja = PySide2.QtCore.Qt.Key.Key_Hangul_PostHanja
    Key_Hangul_PreHanja = PySide2.QtCore.Qt.Key.Key_Hangul_PreHanja
    Key_Hangul_Romaja = PySide2.QtCore.Qt.Key.Key_Hangul_Romaja
    Key_Hangul_Special = PySide2.QtCore.Qt.Key.Key_Hangul_Special
    Key_Hangul_Start = PySide2.QtCore.Qt.Key.Key_Hangul_Start
    Key_Hangup = PySide2.QtCore.Qt.Key.Key_Hangup
    Key_Hankaku = PySide2.QtCore.Qt.Key.Key_Hankaku
    Key_Help = PySide2.QtCore.Qt.Key.Key_Help
    Key_Henkan = PySide2.QtCore.Qt.Key.Key_Henkan
    Key_Hibernate = PySide2.QtCore.Qt.Key.Key_Hibernate
    Key_Hiragana = PySide2.QtCore.Qt.Key.Key_Hiragana
    Key_Hiragana_Katakana = PySide2.QtCore.Qt.Key.Key_Hiragana_Katakana
    Key_History = PySide2.QtCore.Qt.Key.Key_History
    Key_Home = PySide2.QtCore.Qt.Key.Key_Home
    Key_HomePage = PySide2.QtCore.Qt.Key.Key_HomePage
    Key_HotLinks = PySide2.QtCore.Qt.Key.Key_HotLinks
    Key_Hyper_L = PySide2.QtCore.Qt.Key.Key_Hyper_L
    Key_Hyper_R = PySide2.QtCore.Qt.Key.Key_Hyper_R
    Key_hyphen = PySide2.QtCore.Qt.Key.Key_hyphen
    Key_I = PySide2.QtCore.Qt.Key.Key_I
    Key_Iacute = PySide2.QtCore.Qt.Key.Key_Iacute
    Key_Icircumflex = PySide2.QtCore.Qt.Key.Key_Icircumflex
    Key_Idiaeresis = PySide2.QtCore.Qt.Key.Key_Idiaeresis
    Key_Igrave = PySide2.QtCore.Qt.Key.Key_Igrave
    Key_Info = PySide2.QtCore.Qt.Key.Key_Info
    Key_Insert = PySide2.QtCore.Qt.Key.Key_Insert
    Key_iTouch = PySide2.QtCore.Qt.Key.Key_iTouch
    Key_J = PySide2.QtCore.Qt.Key.Key_J
    Key_K = PySide2.QtCore.Qt.Key.Key_K
    Key_Kana_Lock = PySide2.QtCore.Qt.Key.Key_Kana_Lock
    Key_Kana_Shift = PySide2.QtCore.Qt.Key.Key_Kana_Shift
    Key_Kanji = PySide2.QtCore.Qt.Key.Key_Kanji
    Key_Katakana = PySide2.QtCore.Qt.Key.Key_Katakana
    Key_KeyboardBrightnessDown = PySide2.QtCore.Qt.Key.Key_KeyboardBrightnessDown
    Key_KeyboardBrightnessUp = PySide2.QtCore.Qt.Key.Key_KeyboardBrightnessUp
    Key_KeyboardLightOnOff = PySide2.QtCore.Qt.Key.Key_KeyboardLightOnOff
    Key_L = PySide2.QtCore.Qt.Key.Key_L
    Key_LastNumberRedial = PySide2.QtCore.Qt.Key.Key_LastNumberRedial
    Key_Launch0 = PySide2.QtCore.Qt.Key.Key_Launch0
    Key_Launch1 = PySide2.QtCore.Qt.Key.Key_Launch1
    Key_Launch2 = PySide2.QtCore.Qt.Key.Key_Launch2
    Key_Launch3 = PySide2.QtCore.Qt.Key.Key_Launch3
    Key_Launch4 = PySide2.QtCore.Qt.Key.Key_Launch4
    Key_Launch5 = PySide2.QtCore.Qt.Key.Key_Launch5
    Key_Launch6 = PySide2.QtCore.Qt.Key.Key_Launch6
    Key_Launch7 = PySide2.QtCore.Qt.Key.Key_Launch7
    Key_Launch8 = PySide2.QtCore.Qt.Key.Key_Launch8
    Key_Launch9 = PySide2.QtCore.Qt.Key.Key_Launch9
    Key_LaunchA = PySide2.QtCore.Qt.Key.Key_LaunchA
    Key_LaunchB = PySide2.QtCore.Qt.Key.Key_LaunchB
    Key_LaunchC = PySide2.QtCore.Qt.Key.Key_LaunchC
    Key_LaunchD = PySide2.QtCore.Qt.Key.Key_LaunchD
    Key_LaunchE = PySide2.QtCore.Qt.Key.Key_LaunchE
    Key_LaunchF = PySide2.QtCore.Qt.Key.Key_LaunchF
    Key_LaunchG = PySide2.QtCore.Qt.Key.Key_LaunchG
    Key_LaunchH = PySide2.QtCore.Qt.Key.Key_LaunchH
    Key_LaunchMail = PySide2.QtCore.Qt.Key.Key_LaunchMail
    Key_LaunchMedia = PySide2.QtCore.Qt.Key.Key_LaunchMedia
    Key_Left = PySide2.QtCore.Qt.Key.Key_Left
    Key_Less = PySide2.QtCore.Qt.Key.Key_Less
    Key_LightBulb = PySide2.QtCore.Qt.Key.Key_LightBulb
    Key_LogOff = PySide2.QtCore.Qt.Key.Key_LogOff
    Key_M = PySide2.QtCore.Qt.Key.Key_M
    Key_macron = PySide2.QtCore.Qt.Key.Key_macron
    Key_MailForward = PySide2.QtCore.Qt.Key.Key_MailForward
    Key_Market = PySide2.QtCore.Qt.Key.Key_Market
    Key_masculine = PySide2.QtCore.Qt.Key.Key_masculine
    Key_Massyo = PySide2.QtCore.Qt.Key.Key_Massyo
    Key_MediaLast = PySide2.QtCore.Qt.Key.Key_MediaLast
    Key_MediaNext = PySide2.QtCore.Qt.Key.Key_MediaNext
    Key_MediaPause = PySide2.QtCore.Qt.Key.Key_MediaPause
    Key_MediaPlay = PySide2.QtCore.Qt.Key.Key_MediaPlay
    Key_MediaPrevious = PySide2.QtCore.Qt.Key.Key_MediaPrevious
    Key_MediaRecord = PySide2.QtCore.Qt.Key.Key_MediaRecord
    Key_MediaStop = PySide2.QtCore.Qt.Key.Key_MediaStop
    Key_MediaTogglePlayPause = PySide2.QtCore.Qt.Key.Key_MediaTogglePlayPause
    Key_Meeting = PySide2.QtCore.Qt.Key.Key_Meeting
    Key_Memo = PySide2.QtCore.Qt.Key.Key_Memo
    Key_Menu = PySide2.QtCore.Qt.Key.Key_Menu
    Key_MenuKB = PySide2.QtCore.Qt.Key.Key_MenuKB
    Key_MenuPB = PySide2.QtCore.Qt.Key.Key_MenuPB
    Key_Messenger = PySide2.QtCore.Qt.Key.Key_Messenger
    Key_Meta = PySide2.QtCore.Qt.Key.Key_Meta
    Key_MicMute = PySide2.QtCore.Qt.Key.Key_MicMute
    Key_MicVolumeDown = PySide2.QtCore.Qt.Key.Key_MicVolumeDown
    Key_MicVolumeUp = PySide2.QtCore.Qt.Key.Key_MicVolumeUp
    Key_Minus = PySide2.QtCore.Qt.Key.Key_Minus
    Key_Mode_switch = PySide2.QtCore.Qt.Key.Key_Mode_switch
    Key_MonBrightnessDown = PySide2.QtCore.Qt.Key.Key_MonBrightnessDown
    Key_MonBrightnessUp = PySide2.QtCore.Qt.Key.Key_MonBrightnessUp
    Key_mu = PySide2.QtCore.Qt.Key.Key_mu
    Key_Muhenkan = PySide2.QtCore.Qt.Key.Key_Muhenkan
    Key_MultipleCandidate = PySide2.QtCore.Qt.Key.Key_MultipleCandidate
    Key_multiply = PySide2.QtCore.Qt.Key.Key_multiply
    Key_Multi_key = PySide2.QtCore.Qt.Key.Key_Multi_key
    Key_Music = PySide2.QtCore.Qt.Key.Key_Music
    Key_MySites = PySide2.QtCore.Qt.Key.Key_MySites
    Key_N = PySide2.QtCore.Qt.Key.Key_N
    Key_New = PySide2.QtCore.Qt.Key.Key_New
    Key_News = PySide2.QtCore.Qt.Key.Key_News
    Key_No = PySide2.QtCore.Qt.Key.Key_No
    Key_nobreakspace = PySide2.QtCore.Qt.Key.Key_nobreakspace
    Key_notsign = PySide2.QtCore.Qt.Key.Key_notsign
    Key_Ntilde = PySide2.QtCore.Qt.Key.Key_Ntilde
    Key_NumberSign = PySide2.QtCore.Qt.Key.Key_NumberSign
    Key_NumLock = PySide2.QtCore.Qt.Key.Key_NumLock
    Key_O = PySide2.QtCore.Qt.Key.Key_O
    Key_Oacute = PySide2.QtCore.Qt.Key.Key_Oacute
    Key_Ocircumflex = PySide2.QtCore.Qt.Key.Key_Ocircumflex
    Key_Odiaeresis = PySide2.QtCore.Qt.Key.Key_Odiaeresis
    Key_OfficeHome = PySide2.QtCore.Qt.Key.Key_OfficeHome
    Key_Ograve = PySide2.QtCore.Qt.Key.Key_Ograve
    Key_onehalf = PySide2.QtCore.Qt.Key.Key_onehalf
    Key_onequarter = PySide2.QtCore.Qt.Key.Key_onequarter
    Key_onesuperior = PySide2.QtCore.Qt.Key.Key_onesuperior
    Key_Ooblique = PySide2.QtCore.Qt.Key.Key_Ooblique
    Key_Open = PySide2.QtCore.Qt.Key.Key_Open
    Key_OpenUrl = PySide2.QtCore.Qt.Key.Key_OpenUrl
    Key_Option = PySide2.QtCore.Qt.Key.Key_Option
    Key_ordfeminine = PySide2.QtCore.Qt.Key.Key_ordfeminine
    Key_Otilde = PySide2.QtCore.Qt.Key.Key_Otilde
    Key_P = PySide2.QtCore.Qt.Key.Key_P
    Key_PageDown = PySide2.QtCore.Qt.Key.Key_PageDown
    Key_PageUp = PySide2.QtCore.Qt.Key.Key_PageUp
    Key_paragraph = PySide2.QtCore.Qt.Key.Key_paragraph
    Key_ParenLeft = PySide2.QtCore.Qt.Key.Key_ParenLeft
    Key_ParenRight = PySide2.QtCore.Qt.Key.Key_ParenRight
    Key_Paste = PySide2.QtCore.Qt.Key.Key_Paste
    Key_Pause = PySide2.QtCore.Qt.Key.Key_Pause
    Key_Percent = PySide2.QtCore.Qt.Key.Key_Percent
    Key_Period = PySide2.QtCore.Qt.Key.Key_Period
    Key_periodcentered = PySide2.QtCore.Qt.Key.Key_periodcentered
    Key_Phone = PySide2.QtCore.Qt.Key.Key_Phone
    Key_Pictures = PySide2.QtCore.Qt.Key.Key_Pictures
    Key_Play = PySide2.QtCore.Qt.Key.Key_Play
    Key_Plus = PySide2.QtCore.Qt.Key.Key_Plus
    Key_plusminus = PySide2.QtCore.Qt.Key.Key_plusminus
    Key_PowerDown = PySide2.QtCore.Qt.Key.Key_PowerDown
    Key_PowerOff = PySide2.QtCore.Qt.Key.Key_PowerOff
    Key_PreviousCandidate = PySide2.QtCore.Qt.Key.Key_PreviousCandidate
    Key_Print = PySide2.QtCore.Qt.Key.Key_Print
    Key_Printer = PySide2.QtCore.Qt.Key.Key_Printer
    Key_Q = PySide2.QtCore.Qt.Key.Key_Q
    Key_Question = PySide2.QtCore.Qt.Key.Key_Question
    Key_questiondown = PySide2.QtCore.Qt.Key.Key_questiondown
    Key_QuoteDbl = PySide2.QtCore.Qt.Key.Key_QuoteDbl
    Key_QuoteLeft = PySide2.QtCore.Qt.Key.Key_QuoteLeft
    Key_R = PySide2.QtCore.Qt.Key.Key_R
    Key_Red = PySide2.QtCore.Qt.Key.Key_Red
    Key_Redo = PySide2.QtCore.Qt.Key.Key_Redo
    Key_Refresh = PySide2.QtCore.Qt.Key.Key_Refresh
    Key_registered = PySide2.QtCore.Qt.Key.Key_registered
    Key_Reload = PySide2.QtCore.Qt.Key.Key_Reload
    Key_Reply = PySide2.QtCore.Qt.Key.Key_Reply
    Key_Return = PySide2.QtCore.Qt.Key.Key_Return
    Key_Right = PySide2.QtCore.Qt.Key.Key_Right
    Key_Romaji = PySide2.QtCore.Qt.Key.Key_Romaji
    Key_RotateWindows = PySide2.QtCore.Qt.Key.Key_RotateWindows
    Key_RotationKB = PySide2.QtCore.Qt.Key.Key_RotationKB
    Key_RotationPB = PySide2.QtCore.Qt.Key.Key_RotationPB
    Key_S = PySide2.QtCore.Qt.Key.Key_S
    Key_Save = PySide2.QtCore.Qt.Key.Key_Save
    Key_ScreenSaver = PySide2.QtCore.Qt.Key.Key_ScreenSaver
    Key_ScrollLock = PySide2.QtCore.Qt.Key.Key_ScrollLock
    Key_Search = PySide2.QtCore.Qt.Key.Key_Search
    Key_section = PySide2.QtCore.Qt.Key.Key_section
    Key_Select = PySide2.QtCore.Qt.Key.Key_Select
    Key_Semicolon = PySide2.QtCore.Qt.Key.Key_Semicolon
    Key_Send = PySide2.QtCore.Qt.Key.Key_Send
    Key_Settings = PySide2.QtCore.Qt.Key.Key_Settings
    Key_Shift = PySide2.QtCore.Qt.Key.Key_Shift
    Key_Shop = PySide2.QtCore.Qt.Key.Key_Shop
    Key_SingleCandidate = PySide2.QtCore.Qt.Key.Key_SingleCandidate
    Key_Slash = PySide2.QtCore.Qt.Key.Key_Slash
    Key_Sleep = PySide2.QtCore.Qt.Key.Key_Sleep
    Key_Space = PySide2.QtCore.Qt.Key.Key_Space
    Key_Spell = PySide2.QtCore.Qt.Key.Key_Spell
    Key_SplitScreen = PySide2.QtCore.Qt.Key.Key_SplitScreen
    Key_ssharp = PySide2.QtCore.Qt.Key.Key_ssharp
    Key_Standby = PySide2.QtCore.Qt.Key.Key_Standby
    Key_sterling = PySide2.QtCore.Qt.Key.Key_sterling
    Key_Stop = PySide2.QtCore.Qt.Key.Key_Stop
    Key_Subtitle = PySide2.QtCore.Qt.Key.Key_Subtitle
    Key_Super_L = PySide2.QtCore.Qt.Key.Key_Super_L
    Key_Super_R = PySide2.QtCore.Qt.Key.Key_Super_R
    Key_Support = PySide2.QtCore.Qt.Key.Key_Support
    Key_Suspend = PySide2.QtCore.Qt.Key.Key_Suspend
    Key_SysReq = PySide2.QtCore.Qt.Key.Key_SysReq
    Key_T = PySide2.QtCore.Qt.Key.Key_T
    Key_Tab = PySide2.QtCore.Qt.Key.Key_Tab
    Key_TaskPane = PySide2.QtCore.Qt.Key.Key_TaskPane
    Key_Terminal = PySide2.QtCore.Qt.Key.Key_Terminal
    Key_THORN = PySide2.QtCore.Qt.Key.Key_THORN
    Key_threequarters = PySide2.QtCore.Qt.Key.Key_threequarters
    Key_threesuperior = PySide2.QtCore.Qt.Key.Key_threesuperior
    Key_Time = PySide2.QtCore.Qt.Key.Key_Time
    Key_ToDoList = PySide2.QtCore.Qt.Key.Key_ToDoList
    Key_ToggleCallHangup = PySide2.QtCore.Qt.Key.Key_ToggleCallHangup
    Key_Tools = PySide2.QtCore.Qt.Key.Key_Tools
    Key_TopMenu = PySide2.QtCore.Qt.Key.Key_TopMenu
    Key_TouchpadOff = PySide2.QtCore.Qt.Key.Key_TouchpadOff
    Key_TouchpadOn = PySide2.QtCore.Qt.Key.Key_TouchpadOn
    Key_TouchpadToggle = PySide2.QtCore.Qt.Key.Key_TouchpadToggle
    Key_Touroku = PySide2.QtCore.Qt.Key.Key_Touroku
    Key_Travel = PySide2.QtCore.Qt.Key.Key_Travel
    Key_TrebleDown = PySide2.QtCore.Qt.Key.Key_TrebleDown
    Key_TrebleUp = PySide2.QtCore.Qt.Key.Key_TrebleUp
    Key_twosuperior = PySide2.QtCore.Qt.Key.Key_twosuperior
    Key_U = PySide2.QtCore.Qt.Key.Key_U
    Key_Uacute = PySide2.QtCore.Qt.Key.Key_Uacute
    Key_Ucircumflex = PySide2.QtCore.Qt.Key.Key_Ucircumflex
    Key_Udiaeresis = PySide2.QtCore.Qt.Key.Key_Udiaeresis
    Key_Ugrave = PySide2.QtCore.Qt.Key.Key_Ugrave
    Key_Underscore = PySide2.QtCore.Qt.Key.Key_Underscore
    Key_Undo = PySide2.QtCore.Qt.Key.Key_Undo
    Key_unknown = PySide2.QtCore.Qt.Key.Key_unknown
    Key_Up = PySide2.QtCore.Qt.Key.Key_Up
    Key_UWB = PySide2.QtCore.Qt.Key.Key_UWB
    Key_V = PySide2.QtCore.Qt.Key.Key_V
    Key_Video = PySide2.QtCore.Qt.Key.Key_Video
    Key_View = PySide2.QtCore.Qt.Key.Key_View
    Key_VoiceDial = PySide2.QtCore.Qt.Key.Key_VoiceDial
    Key_VolumeDown = PySide2.QtCore.Qt.Key.Key_VolumeDown
    Key_VolumeMute = PySide2.QtCore.Qt.Key.Key_VolumeMute
    Key_VolumeUp = PySide2.QtCore.Qt.Key.Key_VolumeUp
    Key_W = PySide2.QtCore.Qt.Key.Key_W
    Key_WakeUp = PySide2.QtCore.Qt.Key.Key_WakeUp
    Key_WebCam = PySide2.QtCore.Qt.Key.Key_WebCam
    Key_WLAN = PySide2.QtCore.Qt.Key.Key_WLAN
    Key_Word = PySide2.QtCore.Qt.Key.Key_Word
    Key_WWW = PySide2.QtCore.Qt.Key.Key_WWW
    Key_X = PySide2.QtCore.Qt.Key.Key_X
    Key_Xfer = PySide2.QtCore.Qt.Key.Key_Xfer
    Key_Y = PySide2.QtCore.Qt.Key.Key_Y
    Key_Yacute = PySide2.QtCore.Qt.Key.Key_Yacute
    Key_ydiaeresis = PySide2.QtCore.Qt.Key.Key_ydiaeresis
    Key_Yellow = PySide2.QtCore.Qt.Key.Key_Yellow
    Key_yen = PySide2.QtCore.Qt.Key.Key_yen
    Key_Yes = PySide2.QtCore.Qt.Key.Key_Yes
    Key_Z = PySide2.QtCore.Qt.Key.Key_Z
    Key_Zenkaku = PySide2.QtCore.Qt.Key.Key_Zenkaku
    Key_Zenkaku_Hankaku = PySide2.QtCore.Qt.Key.Key_Zenkaku_Hankaku
    Key_Zoom = PySide2.QtCore.Qt.Key.Key_Zoom
    Key_ZoomIn = PySide2.QtCore.Qt.Key.Key_ZoomIn
    Key_ZoomOut = PySide2.QtCore.Qt.Key.Key_ZoomOut
    LandscapeOrientation = PySide2.QtCore.Qt.ScreenOrientation.LandscapeOrientation
    LastCursor = PySide2.QtCore.Qt.CursorShape.LastCursor
    LastGestureType = PySide2.QtCore.Qt.GestureType.LastGestureType
    LayoutDirection = None # (!) real value is "<class 'PySide2.QtCore.Qt.LayoutDirection'>"
    LayoutDirectionAuto = PySide2.QtCore.Qt.LayoutDirection.LayoutDirectionAuto
    LeftArrow = PySide2.QtCore.Qt.ArrowType.LeftArrow
    LeftButton = PySide2.QtCore.Qt.MouseButton.LeftButton
    LeftDockWidgetArea = PySide2.QtCore.Qt.DockWidgetArea.LeftDockWidgetArea
    LeftEdge = PySide2.QtCore.Qt.Edge.LeftEdge
    LeftSection = PySide2.QtCore.Qt.WindowFrameSection.LeftSection
    LeftToolBarArea = PySide2.QtCore.Qt.ToolBarArea.LeftToolBarArea
    LeftToRight = PySide2.QtCore.Qt.LayoutDirection.LeftToRight
    lightGray = PySide2.QtCore.Qt.GlobalColor.lightGray
    LinearGradientPattern = PySide2.QtCore.Qt.BrushStyle.LinearGradientPattern
    LinkAction = PySide2.QtCore.Qt.DropAction.LinkAction
    LinksAccessibleByKeyboard = PySide2.QtCore.Qt.TextInteractionFlag.LinksAccessibleByKeyboard
    LinksAccessibleByMouse = PySide2.QtCore.Qt.TextInteractionFlag.LinksAccessibleByMouse
    LocalDate = PySide2.QtCore.Qt.DateFormat.LocalDate
    LocaleDate = PySide2.QtCore.Qt.DateFormat.LocaleDate
    LocalTime = PySide2.QtCore.Qt.TimeSpec.LocalTime
    LogicalCoordinates = PySide2.QtCore.Qt.CoordinateSystem.LogicalCoordinates
    LogicalMoveStyle = PySide2.QtCore.Qt.CursorMoveStyle.LogicalMoveStyle
    LowEventPriority = PySide2.QtCore.Qt.EventPriority.LowEventPriority
    MacWindowToolBarButtonHint = PySide2.QtCore.Qt.WindowType.MacWindowToolBarButtonHint
    magenta = PySide2.QtCore.Qt.GlobalColor.magenta
    MarkdownText = PySide2.QtCore.Qt.TextFormat.MarkdownText
    MaskInColor = PySide2.QtCore.Qt.MaskMode.MaskInColor
    MaskMode = None # (!) real value is "<class 'PySide2.QtCore.Qt.MaskMode'>"
    MaskOutColor = PySide2.QtCore.Qt.MaskMode.MaskOutColor
    MatchCaseSensitive = PySide2.QtCore.Qt.MatchFlag.MatchCaseSensitive
    MatchContains = PySide2.QtCore.Qt.MatchFlag.MatchContains
    MatchEndsWith = PySide2.QtCore.Qt.MatchFlag.MatchEndsWith
    MatchExactly = PySide2.QtCore.Qt.MatchFlag.MatchExactly
    MatchFixedString = PySide2.QtCore.Qt.MatchFlag.MatchFixedString
    MatchFlag = None # (!) real value is "<class 'PySide2.QtCore.Qt.MatchFlag'>"
    MatchFlags = None # (!) real value is "<class 'PySide2.QtCore.Qt.MatchFlags'>"
    MatchRecursive = PySide2.QtCore.Qt.MatchFlag.MatchRecursive
    MatchRegExp = PySide2.QtCore.Qt.MatchFlag.MatchRegExp
    MatchRegularExpression = PySide2.QtCore.Qt.MatchFlag.MatchRegularExpression
    MatchStartsWith = PySide2.QtCore.Qt.MatchFlag.MatchStartsWith
    MatchWildcard = PySide2.QtCore.Qt.MatchFlag.MatchWildcard
    MatchWrap = PySide2.QtCore.Qt.MatchFlag.MatchWrap
    MaximizeUsingFullscreenGeometryHint = PySide2.QtCore.Qt.WindowType.MaximizeUsingFullscreenGeometryHint
    MaximumSize = PySide2.QtCore.Qt.SizeHint.MaximumSize
    MaxMouseButton = PySide2.QtCore.Qt.MouseButton.MaxMouseButton
    MenuBarFocusReason = PySide2.QtCore.Qt.FocusReason.MenuBarFocusReason
    META = PySide2.QtCore.Qt.Modifier.META
    MetaModifier = PySide2.QtCore.Qt.KeyboardModifier.MetaModifier
    MidButton = PySide2.QtCore.Qt.MouseButton.MidButton
    MiddleButton = PySide2.QtCore.Qt.MouseButton.MiddleButton
    MinimumDescent = PySide2.QtCore.Qt.SizeHint.MinimumDescent
    MinimumSize = PySide2.QtCore.Qt.SizeHint.MinimumSize
    MiterJoin = PySide2.QtCore.Qt.PenJoinStyle.MiterJoin
    Modifier = None # (!) real value is "<class 'PySide2.QtCore.Qt.Modifier'>"
    MODIFIER_MASK = PySide2.QtCore.Qt.Modifier.MODIFIER_MASK
    Monday = PySide2.QtCore.Qt.DayOfWeek.Monday
    MonoOnly = PySide2.QtCore.Qt.ImageConversionFlag.MonoOnly
    MouseButton = None # (!) real value is "<class 'PySide2.QtCore.Qt.MouseButton'>"
    MouseButtonMask = PySide2.QtCore.Qt.MouseButton.MouseButtonMask
    MouseButtons = None # (!) real value is "<class 'PySide2.QtCore.Qt.MouseButtons'>"
    MouseEventCreatedDoubleClick = PySide2.QtCore.Qt.MouseEventFlag.MouseEventCreatedDoubleClick
    MouseEventFlag = None # (!) real value is "<class 'PySide2.QtCore.Qt.MouseEventFlag'>"
    MouseEventFlagMask = PySide2.QtCore.Qt.MouseEventFlag.MouseEventFlagMask
    MouseEventFlags = None # (!) real value is "<class 'PySide2.QtCore.Qt.MouseEventFlags'>"
    MouseEventNotSynthesized = PySide2.QtCore.Qt.MouseEventSource.MouseEventNotSynthesized
    MouseEventSource = None # (!) real value is "<class 'PySide2.QtCore.Qt.MouseEventSource'>"
    MouseEventSynthesizedByApplication = PySide2.QtCore.Qt.MouseEventSource.MouseEventSynthesizedByApplication
    MouseEventSynthesizedByQt = PySide2.QtCore.Qt.MouseEventSource.MouseEventSynthesizedByQt
    MouseEventSynthesizedBySystem = PySide2.QtCore.Qt.MouseEventSource.MouseEventSynthesizedBySystem
    MouseFocusReason = PySide2.QtCore.Qt.FocusReason.MouseFocusReason
    MoveAction = PySide2.QtCore.Qt.DropAction.MoveAction
    MPenCapStyle = PySide2.QtCore.Qt.PenCapStyle.MPenCapStyle
    MPenJoinStyle = PySide2.QtCore.Qt.PenJoinStyle.MPenJoinStyle
    MPenStyle = PySide2.QtCore.Qt.PenStyle.MPenStyle
    MSWindowsFixedSizeDialogHint = PySide2.QtCore.Qt.WindowType.MSWindowsFixedSizeDialogHint
    MSWindowsOwnDC = PySide2.QtCore.Qt.WindowType.MSWindowsOwnDC
    NativeGestureType = None # (!) real value is "<class 'PySide2.QtCore.Qt.NativeGestureType'>"
    NavigationMode = None # (!) real value is "<class 'PySide2.QtCore.Qt.NavigationMode'>"
    NavigationModeCursorAuto = PySide2.QtCore.Qt.NavigationMode.NavigationModeCursorAuto
    NavigationModeCursorForceVisible = PySide2.QtCore.Qt.NavigationMode.NavigationModeCursorForceVisible
    NavigationModeKeypadDirectional = PySide2.QtCore.Qt.NavigationMode.NavigationModeKeypadDirectional
    NavigationModeKeypadTabOrder = PySide2.QtCore.Qt.NavigationMode.NavigationModeKeypadTabOrder
    NavigationModeNone = PySide2.QtCore.Qt.NavigationMode.NavigationModeNone
    NDockWidgetAreas = PySide2.QtCore.Qt.DockWidgetAreaSizes.NDockWidgetAreas
    NoAlpha = PySide2.QtCore.Qt.ImageConversionFlag.NoAlpha
    NoArrow = PySide2.QtCore.Qt.ArrowType.NoArrow
    NoBrush = PySide2.QtCore.Qt.BrushStyle.NoBrush
    NoButton = PySide2.QtCore.Qt.MouseButton.NoButton
    NoClip = PySide2.QtCore.Qt.ClipOperation.NoClip
    NoContextMenu = PySide2.QtCore.Qt.ContextMenuPolicy.NoContextMenu
    NoDockWidgetArea = PySide2.QtCore.Qt.DockWidgetArea.NoDockWidgetArea
    NoDropShadowWindowHint = PySide2.QtCore.Qt.WindowType.NoDropShadowWindowHint
    NoFocus = PySide2.QtCore.Qt.FocusPolicy.NoFocus
    NoFocusReason = PySide2.QtCore.Qt.FocusReason.NoFocusReason
    NoFormatConversion = PySide2.QtCore.Qt.ImageConversionFlag.NoFormatConversion
    NoGesture = PySide2.QtCore.Qt.GestureState.NoGesture
    NoItemFlags = PySide2.QtCore.Qt.ItemFlag.NoItemFlags
    NoModifier = PySide2.QtCore.Qt.KeyboardModifier.NoModifier
    NonModal = PySide2.QtCore.Qt.WindowModality.NonModal
    NoOpaqueDetection = PySide2.QtCore.Qt.ImageConversionFlag.NoOpaqueDetection
    NoPen = PySide2.QtCore.Qt.PenStyle.NoPen
    NormalEventPriority = PySide2.QtCore.Qt.EventPriority.NormalEventPriority
    NoScrollPhase = PySide2.QtCore.Qt.ScrollPhase.NoScrollPhase
    NoSection = PySide2.QtCore.Qt.WindowFrameSection.NoSection
    NoTabFocus = PySide2.QtCore.Qt.TabFocusBehavior.NoTabFocus
    NoTextInteraction = PySide2.QtCore.Qt.TextInteractionFlag.NoTextInteraction
    NoToolBarArea = PySide2.QtCore.Qt.ToolBarArea.NoToolBarArea
    NSizeHints = PySide2.QtCore.Qt.SizeHint.NSizeHints
    NToolBarAreas = PySide2.QtCore.Qt.ToolBarAreaSizes.NToolBarAreas
    OddEvenFill = PySide2.QtCore.Qt.FillRule.OddEvenFill
    OffsetFromUTC = PySide2.QtCore.Qt.TimeSpec.OffsetFromUTC
    OpaqueMode = PySide2.QtCore.Qt.BGMode.OpaqueMode
    OpenHandCursor = PySide2.QtCore.Qt.CursorShape.OpenHandCursor
    OrderedAlphaDither = PySide2.QtCore.Qt.ImageConversionFlag.OrderedAlphaDither
    OrderedDither = PySide2.QtCore.Qt.ImageConversionFlag.OrderedDither
    Orientation = None # (!) real value is "<class 'PySide2.QtCore.Qt.Orientation'>"
    Orientations = None # (!) real value is "<class 'PySide2.QtCore.Qt.Orientations'>"
    OtherFocusReason = PySide2.QtCore.Qt.FocusReason.OtherFocusReason
    PanGesture = PySide2.QtCore.Qt.GestureType.PanGesture
    PanNativeGesture = PySide2.QtCore.Qt.NativeGestureType.PanNativeGesture
    PartiallyChecked = PySide2.QtCore.Qt.CheckState.PartiallyChecked
    PenCapStyle = None # (!) real value is "<class 'PySide2.QtCore.Qt.PenCapStyle'>"
    PenJoinStyle = None # (!) real value is "<class 'PySide2.QtCore.Qt.PenJoinStyle'>"
    PenStyle = None # (!) real value is "<class 'PySide2.QtCore.Qt.PenStyle'>"
    PinchGesture = PySide2.QtCore.Qt.GestureType.PinchGesture
    PlainText = PySide2.QtCore.Qt.TextFormat.PlainText
    PointingHandCursor = PySide2.QtCore.Qt.CursorShape.PointingHandCursor
    Popup = PySide2.QtCore.Qt.WindowType.Popup
    PopupFocusReason = PySide2.QtCore.Qt.FocusReason.PopupFocusReason
    PortraitOrientation = PySide2.QtCore.Qt.ScreenOrientation.PortraitOrientation
    PreciseTimer = PySide2.QtCore.Qt.TimerType.PreciseTimer
    PreferDither = PySide2.QtCore.Qt.ImageConversionFlag.PreferDither
    PreferredSize = PySide2.QtCore.Qt.SizeHint.PreferredSize
    PreventContextMenu = PySide2.QtCore.Qt.ContextMenuPolicy.PreventContextMenu
    PrimaryOrientation = PySide2.QtCore.Qt.ScreenOrientation.PrimaryOrientation
    QueuedConnection = PySide2.QtCore.Qt.ConnectionType.QueuedConnection
    RadialGradientPattern = PySide2.QtCore.Qt.BrushStyle.RadialGradientPattern
    ReceivePartialGestures = PySide2.QtCore.Qt.GestureFlag.ReceivePartialGestures
    red = PySide2.QtCore.Qt.GlobalColor.red
    RelativeSize = PySide2.QtCore.Qt.SizeMode.RelativeSize
    RepeatTile = PySide2.QtCore.Qt.TileRule.RepeatTile
    ReplaceClip = PySide2.QtCore.Qt.ClipOperation.ReplaceClip
    ReplaceSelection = PySide2.QtCore.Qt.ItemSelectionOperation.ReplaceSelection
    RFC2822Date = PySide2.QtCore.Qt.DateFormat.RFC2822Date
    RichText = PySide2.QtCore.Qt.TextFormat.RichText
    RightArrow = PySide2.QtCore.Qt.ArrowType.RightArrow
    RightButton = PySide2.QtCore.Qt.MouseButton.RightButton
    RightDockWidgetArea = PySide2.QtCore.Qt.DockWidgetArea.RightDockWidgetArea
    RightEdge = PySide2.QtCore.Qt.Edge.RightEdge
    RightSection = PySide2.QtCore.Qt.WindowFrameSection.RightSection
    RightToLeft = PySide2.QtCore.Qt.LayoutDirection.RightToLeft
    RightToolBarArea = PySide2.QtCore.Qt.ToolBarArea.RightToolBarArea
    RotateNativeGesture = PySide2.QtCore.Qt.NativeGestureType.RotateNativeGesture
    RoundCap = PySide2.QtCore.Qt.PenCapStyle.RoundCap
    RoundJoin = PySide2.QtCore.Qt.PenJoinStyle.RoundJoin
    RoundTile = PySide2.QtCore.Qt.TileRule.RoundTile
    Saturday = PySide2.QtCore.Qt.DayOfWeek.Saturday
    ScreenOrientation = None # (!) real value is "<class 'PySide2.QtCore.Qt.ScreenOrientation'>"
    ScreenOrientations = None # (!) real value is "<class 'PySide2.QtCore.Qt.ScreenOrientations'>"
    ScrollBarAlwaysOff = PySide2.QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff
    ScrollBarAlwaysOn = PySide2.QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOn
    ScrollBarAsNeeded = PySide2.QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded
    ScrollBarPolicy = None # (!) real value is "<class 'PySide2.QtCore.Qt.ScrollBarPolicy'>"
    ScrollBegin = PySide2.QtCore.Qt.ScrollPhase.ScrollBegin
    ScrollEnd = PySide2.QtCore.Qt.ScrollPhase.ScrollEnd
    ScrollMomentum = PySide2.QtCore.Qt.ScrollPhase.ScrollMomentum
    ScrollPhase = None # (!) real value is "<class 'PySide2.QtCore.Qt.ScrollPhase'>"
    ScrollUpdate = PySide2.QtCore.Qt.ScrollPhase.ScrollUpdate
    Sheet = PySide2.QtCore.Qt.WindowType.Sheet
    SHIFT = PySide2.QtCore.Qt.Modifier.SHIFT
    ShiftModifier = PySide2.QtCore.Qt.KeyboardModifier.ShiftModifier
    ShortcutContext = None # (!) real value is "<class 'PySide2.QtCore.Qt.ShortcutContext'>"
    ShortcutFocusReason = PySide2.QtCore.Qt.FocusReason.ShortcutFocusReason
    SizeAllCursor = PySide2.QtCore.Qt.CursorShape.SizeAllCursor
    SizeBDiagCursor = PySide2.QtCore.Qt.CursorShape.SizeBDiagCursor
    SizeFDiagCursor = PySide2.QtCore.Qt.CursorShape.SizeFDiagCursor
    SizeHint = None # (!) real value is "<class 'PySide2.QtCore.Qt.SizeHint'>"
    SizeHintRole = PySide2.QtCore.Qt.ItemDataRole.SizeHintRole
    SizeHorCursor = PySide2.QtCore.Qt.CursorShape.SizeHorCursor
    SizeMode = None # (!) real value is "<class 'PySide2.QtCore.Qt.SizeMode'>"
    SizeVerCursor = PySide2.QtCore.Qt.CursorShape.SizeVerCursor
    SkipEmptyParts = PySide2.QtCore.Qt.SplitBehaviorFlags.SkipEmptyParts
    SmartZoomNativeGesture = PySide2.QtCore.Qt.NativeGestureType.SmartZoomNativeGesture
    SmoothTransformation = PySide2.QtCore.Qt.TransformationMode.SmoothTransformation
    SolidLine = PySide2.QtCore.Qt.PenStyle.SolidLine
    SolidPattern = PySide2.QtCore.Qt.BrushStyle.SolidPattern
    SortOrder = None # (!) real value is "<class 'PySide2.QtCore.Qt.SortOrder'>"
    SplashScreen = PySide2.QtCore.Qt.WindowType.SplashScreen
    SplitBehavior = None # (!) real value is "<class 'PySide2.QtCore.Qt.SplitBehavior'>"
    SplitBehaviorFlags = None # (!) real value is "<class 'PySide2.QtCore.Qt.SplitBehaviorFlags'>"
    SplitHCursor = PySide2.QtCore.Qt.CursorShape.SplitHCursor
    SplitVCursor = PySide2.QtCore.Qt.CursorShape.SplitVCursor
    SquareCap = PySide2.QtCore.Qt.PenCapStyle.SquareCap
    StatusTipPropertyRole = PySide2.QtCore.Qt.ItemDataRole.StatusTipPropertyRole
    StatusTipRole = PySide2.QtCore.Qt.ItemDataRole.StatusTipRole
    StretchTile = PySide2.QtCore.Qt.TileRule.StretchTile
    StrongFocus = PySide2.QtCore.Qt.FocusPolicy.StrongFocus
    SubWindow = PySide2.QtCore.Qt.WindowType.SubWindow
    Sunday = PySide2.QtCore.Qt.DayOfWeek.Sunday
    SvgMiterJoin = PySide2.QtCore.Qt.PenJoinStyle.SvgMiterJoin
    SwipeGesture = PySide2.QtCore.Qt.GestureType.SwipeGesture
    SwipeNativeGesture = PySide2.QtCore.Qt.NativeGestureType.SwipeNativeGesture
    SystemLocaleDate = PySide2.QtCore.Qt.DateFormat.SystemLocaleDate
    SystemLocaleLongDate = PySide2.QtCore.Qt.DateFormat.SystemLocaleLongDate
    SystemLocaleShortDate = PySide2.QtCore.Qt.DateFormat.SystemLocaleShortDate
    TabFocus = PySide2.QtCore.Qt.FocusPolicy.TabFocus
    TabFocusAllControls = PySide2.QtCore.Qt.TabFocusBehavior.TabFocusAllControls
    TabFocusBehavior = None # (!) real value is "<class 'PySide2.QtCore.Qt.TabFocusBehavior'>"
    TabFocusListControls = PySide2.QtCore.Qt.TabFocusBehavior.TabFocusListControls
    TabFocusReason = PySide2.QtCore.Qt.FocusReason.TabFocusReason
    TabFocusTextControls = PySide2.QtCore.Qt.TabFocusBehavior.TabFocusTextControls
    TapAndHoldGesture = PySide2.QtCore.Qt.GestureType.TapAndHoldGesture
    TapGesture = PySide2.QtCore.Qt.GestureType.TapGesture
    TargetMoveAction = PySide2.QtCore.Qt.DropAction.TargetMoveAction
    TaskButton = PySide2.QtCore.Qt.MouseButton.TaskButton
    TextAlignmentRole = PySide2.QtCore.Qt.ItemDataRole.TextAlignmentRole
    TextBrowserInteraction = PySide2.QtCore.Qt.TextInteractionFlag.TextBrowserInteraction
    TextBypassShaping = PySide2.QtCore.Qt.TextFlag.TextBypassShaping
    TextColorRole = PySide2.QtCore.Qt.ItemDataRole.TextColorRole
    TextDate = PySide2.QtCore.Qt.DateFormat.TextDate
    TextDontClip = PySide2.QtCore.Qt.TextFlag.TextDontClip
    TextDontPrint = PySide2.QtCore.Qt.TextFlag.TextDontPrint
    TextEditable = PySide2.QtCore.Qt.TextInteractionFlag.TextEditable
    TextEditorInteraction = PySide2.QtCore.Qt.TextInteractionFlag.TextEditorInteraction
    TextElideMode = None # (!) real value is "<class 'PySide2.QtCore.Qt.TextElideMode'>"
    TextExpandTabs = PySide2.QtCore.Qt.TextFlag.TextExpandTabs
    TextFlag = None # (!) real value is "<class 'PySide2.QtCore.Qt.TextFlag'>"
    TextForceLeftToRight = PySide2.QtCore.Qt.TextFlag.TextForceLeftToRight
    TextForceRightToLeft = PySide2.QtCore.Qt.TextFlag.TextForceRightToLeft
    TextFormat = None # (!) real value is "<class 'PySide2.QtCore.Qt.TextFormat'>"
    TextHideMnemonic = PySide2.QtCore.Qt.TextFlag.TextHideMnemonic
    TextIncludeTrailingSpaces = PySide2.QtCore.Qt.TextFlag.TextIncludeTrailingSpaces
    TextInteractionFlag = None # (!) real value is "<class 'PySide2.QtCore.Qt.TextInteractionFlag'>"
    TextInteractionFlags = None # (!) real value is "<class 'PySide2.QtCore.Qt.TextInteractionFlags'>"
    TextJustificationForced = PySide2.QtCore.Qt.TextFlag.TextJustificationForced
    TextLongestVariant = PySide2.QtCore.Qt.TextFlag.TextLongestVariant
    TextSelectableByKeyboard = PySide2.QtCore.Qt.TextInteractionFlag.TextSelectableByKeyboard
    TextSelectableByMouse = PySide2.QtCore.Qt.TextInteractionFlag.TextSelectableByMouse
    TextShowMnemonic = PySide2.QtCore.Qt.TextFlag.TextShowMnemonic
    TextSingleLine = PySide2.QtCore.Qt.TextFlag.TextSingleLine
    TexturePattern = PySide2.QtCore.Qt.BrushStyle.TexturePattern
    TextWordWrap = PySide2.QtCore.Qt.TextFlag.TextWordWrap
    TextWrapAnywhere = PySide2.QtCore.Qt.TextFlag.TextWrapAnywhere
    ThresholdAlphaDither = PySide2.QtCore.Qt.ImageConversionFlag.ThresholdAlphaDither
    ThresholdDither = PySide2.QtCore.Qt.ImageConversionFlag.ThresholdDither
    Thursday = PySide2.QtCore.Qt.DayOfWeek.Thursday
    TileRule = None # (!) real value is "<class 'PySide2.QtCore.Qt.TileRule'>"
    TimerType = None # (!) real value is "<class 'PySide2.QtCore.Qt.TimerType'>"
    TimeSpec = None # (!) real value is "<class 'PySide2.QtCore.Qt.TimeSpec'>"
    TimeZone = PySide2.QtCore.Qt.TimeSpec.TimeZone
    TitleBarArea = PySide2.QtCore.Qt.WindowFrameSection.TitleBarArea
    Tool = PySide2.QtCore.Qt.WindowType.Tool
    ToolBarArea = None # (!) real value is "<class 'PySide2.QtCore.Qt.ToolBarArea'>"
    ToolBarAreas = None # (!) real value is "<class 'PySide2.QtCore.Qt.ToolBarAreas'>"
    ToolBarAreaSizes = None # (!) real value is "<class 'PySide2.QtCore.Qt.ToolBarAreaSizes'>"
    ToolBarArea_Mask = PySide2.QtCore.Qt.ToolBarArea.ToolBarArea_Mask
    ToolButtonFollowStyle = PySide2.QtCore.Qt.ToolButtonStyle.ToolButtonFollowStyle
    ToolButtonIconOnly = PySide2.QtCore.Qt.ToolButtonStyle.ToolButtonIconOnly
    ToolButtonStyle = None # (!) real value is "<class 'PySide2.QtCore.Qt.ToolButtonStyle'>"
    ToolButtonTextBesideIcon = PySide2.QtCore.Qt.ToolButtonStyle.ToolButtonTextBesideIcon
    ToolButtonTextOnly = PySide2.QtCore.Qt.ToolButtonStyle.ToolButtonTextOnly
    ToolButtonTextUnderIcon = PySide2.QtCore.Qt.ToolButtonStyle.ToolButtonTextUnderIcon
    ToolTip = PySide2.QtCore.Qt.WindowType.ToolTip
    ToolTipPropertyRole = PySide2.QtCore.Qt.ItemDataRole.ToolTipPropertyRole
    ToolTipRole = PySide2.QtCore.Qt.ItemDataRole.ToolTipRole
    TopDockWidgetArea = PySide2.QtCore.Qt.DockWidgetArea.TopDockWidgetArea
    TopEdge = PySide2.QtCore.Qt.Edge.TopEdge
    TopLeftCorner = PySide2.QtCore.Qt.Corner.TopLeftCorner
    TopLeftSection = PySide2.QtCore.Qt.WindowFrameSection.TopLeftSection
    TopRightCorner = PySide2.QtCore.Qt.Corner.TopRightCorner
    TopRightSection = PySide2.QtCore.Qt.WindowFrameSection.TopRightSection
    TopSection = PySide2.QtCore.Qt.WindowFrameSection.TopSection
    TopToolBarArea = PySide2.QtCore.Qt.ToolBarArea.TopToolBarArea
    TouchPointMoved = PySide2.QtCore.Qt.TouchPointState.TouchPointMoved
    TouchPointPressed = PySide2.QtCore.Qt.TouchPointState.TouchPointPressed
    TouchPointReleased = PySide2.QtCore.Qt.TouchPointState.TouchPointReleased
    TouchPointState = None # (!) real value is "<class 'PySide2.QtCore.Qt.TouchPointState'>"
    TouchPointStates = None # (!) real value is "<class 'PySide2.QtCore.Qt.TouchPointStates'>"
    TouchPointStationary = PySide2.QtCore.Qt.TouchPointState.TouchPointStationary
    TransformationMode = None # (!) real value is "<class 'PySide2.QtCore.Qt.TransformationMode'>"
    transparent = PySide2.QtCore.Qt.GlobalColor.transparent
    TransparentMode = PySide2.QtCore.Qt.BGMode.TransparentMode
    Tuesday = PySide2.QtCore.Qt.DayOfWeek.Tuesday
    UIEffect = None # (!) real value is "<class 'PySide2.QtCore.Qt.UIEffect'>"
    UI_AnimateCombo = PySide2.QtCore.Qt.UIEffect.UI_AnimateCombo
    UI_AnimateMenu = PySide2.QtCore.Qt.UIEffect.UI_AnimateMenu
    UI_AnimateToolBox = PySide2.QtCore.Qt.UIEffect.UI_AnimateToolBox
    UI_AnimateTooltip = PySide2.QtCore.Qt.UIEffect.UI_AnimateTooltip
    UI_FadeMenu = PySide2.QtCore.Qt.UIEffect.UI_FadeMenu
    UI_FadeTooltip = PySide2.QtCore.Qt.UIEffect.UI_FadeTooltip
    UI_General = PySide2.QtCore.Qt.UIEffect.UI_General
    Unchecked = PySide2.QtCore.Qt.CheckState.Unchecked
    UNICODE_ACCEL = PySide2.QtCore.Qt.Modifier.UNICODE_ACCEL
    UniqueConnection = PySide2.QtCore.Qt.ConnectionType.UniqueConnection
    UpArrow = PySide2.QtCore.Qt.ArrowType.UpArrow
    UpArrowCursor = PySide2.QtCore.Qt.CursorShape.UpArrowCursor
    UserRole = PySide2.QtCore.Qt.ItemDataRole.UserRole
    UTC = PySide2.QtCore.Qt.TimeSpec.UTC
    VerPattern = PySide2.QtCore.Qt.BrushStyle.VerPattern
    Vertical = PySide2.QtCore.Qt.Orientation.Vertical
    VeryCoarseTimer = PySide2.QtCore.Qt.TimerType.VeryCoarseTimer
    VisualMoveStyle = PySide2.QtCore.Qt.CursorMoveStyle.VisualMoveStyle
    WaitCursor = PySide2.QtCore.Qt.CursorShape.WaitCursor
    WA_AcceptDrops = PySide2.QtCore.Qt.WidgetAttribute.WA_AcceptDrops
    WA_AcceptTouchEvents = PySide2.QtCore.Qt.WidgetAttribute.WA_AcceptTouchEvents
    WA_AlwaysShowToolTips = PySide2.QtCore.Qt.WidgetAttribute.WA_AlwaysShowToolTips
    WA_AlwaysStackOnTop = PySide2.QtCore.Qt.WidgetAttribute.WA_AlwaysStackOnTop
    WA_AttributeCount = PySide2.QtCore.Qt.WidgetAttribute.WA_AttributeCount
    WA_CanHostQMdiSubWindowTitleBar = PySide2.QtCore.Qt.WidgetAttribute.WA_CanHostQMdiSubWindowTitleBar
    WA_ContentsMarginsRespectsSafeArea = PySide2.QtCore.Qt.WidgetAttribute.WA_ContentsMarginsRespectsSafeArea
    WA_ContentsPropagated = PySide2.QtCore.Qt.WidgetAttribute.WA_ContentsPropagated
    WA_CustomWhatsThis = PySide2.QtCore.Qt.WidgetAttribute.WA_CustomWhatsThis
    WA_DeleteOnClose = PySide2.QtCore.Qt.WidgetAttribute.WA_DeleteOnClose
    WA_Disabled = PySide2.QtCore.Qt.WidgetAttribute.WA_Disabled
    WA_DontCreateNativeAncestors = PySide2.QtCore.Qt.WidgetAttribute.WA_DontCreateNativeAncestors
    WA_DontShowOnScreen = PySide2.QtCore.Qt.WidgetAttribute.WA_DontShowOnScreen
    WA_DropSiteRegistered = PySide2.QtCore.Qt.WidgetAttribute.WA_DropSiteRegistered
    WA_ForceAcceptDrops = PySide2.QtCore.Qt.WidgetAttribute.WA_ForceAcceptDrops
    WA_ForceDisabled = PySide2.QtCore.Qt.WidgetAttribute.WA_ForceDisabled
    WA_ForceUpdatesDisabled = PySide2.QtCore.Qt.WidgetAttribute.WA_ForceUpdatesDisabled
    WA_GrabbedShortcut = PySide2.QtCore.Qt.WidgetAttribute.WA_GrabbedShortcut
    WA_GroupLeader = PySide2.QtCore.Qt.WidgetAttribute.WA_GroupLeader
    WA_Hover = PySide2.QtCore.Qt.WidgetAttribute.WA_Hover
    WA_InputMethodEnabled = PySide2.QtCore.Qt.WidgetAttribute.WA_InputMethodEnabled
    WA_InputMethodTransparent = PySide2.QtCore.Qt.WidgetAttribute.WA_InputMethodTransparent
    WA_InvalidSize = PySide2.QtCore.Qt.WidgetAttribute.WA_InvalidSize
    WA_KeyboardFocusChange = PySide2.QtCore.Qt.WidgetAttribute.WA_KeyboardFocusChange
    WA_KeyCompression = PySide2.QtCore.Qt.WidgetAttribute.WA_KeyCompression
    WA_LaidOut = PySide2.QtCore.Qt.WidgetAttribute.WA_LaidOut
    WA_LayoutOnEntireRect = PySide2.QtCore.Qt.WidgetAttribute.WA_LayoutOnEntireRect
    WA_LayoutUsesWidgetRect = PySide2.QtCore.Qt.WidgetAttribute.WA_LayoutUsesWidgetRect
    WA_MacAlwaysShowToolWindow = PySide2.QtCore.Qt.WidgetAttribute.WA_MacAlwaysShowToolWindow
    WA_MacBrushedMetal = PySide2.QtCore.Qt.WidgetAttribute.WA_MacBrushedMetal
    WA_MacFrameworkScaled = PySide2.QtCore.Qt.WidgetAttribute.WA_MacFrameworkScaled
    WA_MacMetalStyle = PySide2.QtCore.Qt.WidgetAttribute.WA_MacMetalStyle
    WA_MacMiniSize = PySide2.QtCore.Qt.WidgetAttribute.WA_MacMiniSize
    WA_MacNoClickThrough = PySide2.QtCore.Qt.WidgetAttribute.WA_MacNoClickThrough
    WA_MacNormalSize = PySide2.QtCore.Qt.WidgetAttribute.WA_MacNormalSize
    WA_MacNoShadow = PySide2.QtCore.Qt.WidgetAttribute.WA_MacNoShadow
    WA_MacOpaqueSizeGrip = PySide2.QtCore.Qt.WidgetAttribute.WA_MacOpaqueSizeGrip
    WA_MacShowFocusRect = PySide2.QtCore.Qt.WidgetAttribute.WA_MacShowFocusRect
    WA_MacSmallSize = PySide2.QtCore.Qt.WidgetAttribute.WA_MacSmallSize
    WA_MacVariableSize = PySide2.QtCore.Qt.WidgetAttribute.WA_MacVariableSize
    WA_Mapped = PySide2.QtCore.Qt.WidgetAttribute.WA_Mapped
    WA_MouseNoMask = PySide2.QtCore.Qt.WidgetAttribute.WA_MouseNoMask
    WA_MouseTracking = PySide2.QtCore.Qt.WidgetAttribute.WA_MouseTracking
    WA_Moved = PySide2.QtCore.Qt.WidgetAttribute.WA_Moved
    WA_MSWindowsUseDirect3D = PySide2.QtCore.Qt.WidgetAttribute.WA_MSWindowsUseDirect3D
    WA_NativeWindow = PySide2.QtCore.Qt.WidgetAttribute.WA_NativeWindow
    WA_NoBackground = PySide2.QtCore.Qt.WidgetAttribute.WA_NoBackground
    WA_NoChildEventsForParent = PySide2.QtCore.Qt.WidgetAttribute.WA_NoChildEventsForParent
    WA_NoChildEventsFromChildren = PySide2.QtCore.Qt.WidgetAttribute.WA_NoChildEventsFromChildren
    WA_NoMousePropagation = PySide2.QtCore.Qt.WidgetAttribute.WA_NoMousePropagation
    WA_NoMouseReplay = PySide2.QtCore.Qt.WidgetAttribute.WA_NoMouseReplay
    WA_NoSystemBackground = PySide2.QtCore.Qt.WidgetAttribute.WA_NoSystemBackground
    WA_NoX11EventCompression = PySide2.QtCore.Qt.WidgetAttribute.WA_NoX11EventCompression
    WA_OpaquePaintEvent = PySide2.QtCore.Qt.WidgetAttribute.WA_OpaquePaintEvent
    WA_OutsideWSRange = PySide2.QtCore.Qt.WidgetAttribute.WA_OutsideWSRange
    WA_PaintOnScreen = PySide2.QtCore.Qt.WidgetAttribute.WA_PaintOnScreen
    WA_PaintUnclipped = PySide2.QtCore.Qt.WidgetAttribute.WA_PaintUnclipped
    WA_PendingMoveEvent = PySide2.QtCore.Qt.WidgetAttribute.WA_PendingMoveEvent
    WA_PendingResizeEvent = PySide2.QtCore.Qt.WidgetAttribute.WA_PendingResizeEvent
    WA_PendingUpdate = PySide2.QtCore.Qt.WidgetAttribute.WA_PendingUpdate
    WA_QuitOnClose = PySide2.QtCore.Qt.WidgetAttribute.WA_QuitOnClose
    WA_Resized = PySide2.QtCore.Qt.WidgetAttribute.WA_Resized
    WA_RightToLeft = PySide2.QtCore.Qt.WidgetAttribute.WA_RightToLeft
    WA_SetCursor = PySide2.QtCore.Qt.WidgetAttribute.WA_SetCursor
    WA_SetFont = PySide2.QtCore.Qt.WidgetAttribute.WA_SetFont
    WA_SetLayoutDirection = PySide2.QtCore.Qt.WidgetAttribute.WA_SetLayoutDirection
    WA_SetLocale = PySide2.QtCore.Qt.WidgetAttribute.WA_SetLocale
    WA_SetPalette = PySide2.QtCore.Qt.WidgetAttribute.WA_SetPalette
    WA_SetStyle = PySide2.QtCore.Qt.WidgetAttribute.WA_SetStyle
    WA_SetWindowIcon = PySide2.QtCore.Qt.WidgetAttribute.WA_SetWindowIcon
    WA_SetWindowModality = PySide2.QtCore.Qt.WidgetAttribute.WA_SetWindowModality
    WA_ShowModal = PySide2.QtCore.Qt.WidgetAttribute.WA_ShowModal
    WA_ShowWithoutActivating = PySide2.QtCore.Qt.WidgetAttribute.WA_ShowWithoutActivating
    WA_StaticContents = PySide2.QtCore.Qt.WidgetAttribute.WA_StaticContents
    WA_StyledBackground = PySide2.QtCore.Qt.WidgetAttribute.WA_StyledBackground
    WA_StyleSheet = PySide2.QtCore.Qt.WidgetAttribute.WA_StyleSheet
    WA_StyleSheetTarget = PySide2.QtCore.Qt.WidgetAttribute.WA_StyleSheetTarget
    WA_TabletTracking = PySide2.QtCore.Qt.WidgetAttribute.WA_TabletTracking
    WA_TintedBackground = PySide2.QtCore.Qt.WidgetAttribute.WA_TintedBackground
    WA_TouchPadAcceptSingleTouchEvents = PySide2.QtCore.Qt.WidgetAttribute.WA_TouchPadAcceptSingleTouchEvents
    WA_TranslucentBackground = PySide2.QtCore.Qt.WidgetAttribute.WA_TranslucentBackground
    WA_TransparentForMouseEvents = PySide2.QtCore.Qt.WidgetAttribute.WA_TransparentForMouseEvents
    WA_UnderMouse = PySide2.QtCore.Qt.WidgetAttribute.WA_UnderMouse
    WA_UpdatesDisabled = PySide2.QtCore.Qt.WidgetAttribute.WA_UpdatesDisabled
    WA_WindowModified = PySide2.QtCore.Qt.WidgetAttribute.WA_WindowModified
    WA_WindowPropagation = PySide2.QtCore.Qt.WidgetAttribute.WA_WindowPropagation
    WA_WState_AcceptedTouchBeginEvent = PySide2.QtCore.Qt.WidgetAttribute.WA_WState_AcceptedTouchBeginEvent
    WA_WState_CompressKeys = PySide2.QtCore.Qt.WidgetAttribute.WA_WState_CompressKeys
    WA_WState_ConfigPending = PySide2.QtCore.Qt.WidgetAttribute.WA_WState_ConfigPending
    WA_WState_Created = PySide2.QtCore.Qt.WidgetAttribute.WA_WState_Created
    WA_WState_DND = PySide2.QtCore.Qt.WidgetAttribute.WA_WState_DND
    WA_WState_ExplicitShowHide = PySide2.QtCore.Qt.WidgetAttribute.WA_WState_ExplicitShowHide
    WA_WState_Hidden = PySide2.QtCore.Qt.WidgetAttribute.WA_WState_Hidden
    WA_WState_InPaintEvent = PySide2.QtCore.Qt.WidgetAttribute.WA_WState_InPaintEvent
    WA_WState_OwnSizePolicy = PySide2.QtCore.Qt.WidgetAttribute.WA_WState_OwnSizePolicy
    WA_WState_Polished = PySide2.QtCore.Qt.WidgetAttribute.WA_WState_Polished
    WA_WState_Reparented = PySide2.QtCore.Qt.WidgetAttribute.WA_WState_Reparented
    WA_WState_Visible = PySide2.QtCore.Qt.WidgetAttribute.WA_WState_Visible
    WA_WState_WindowOpacitySet = PySide2.QtCore.Qt.WidgetAttribute.WA_WState_WindowOpacitySet
    WA_X11BypassTransientForHint = PySide2.QtCore.Qt.WidgetAttribute.WA_X11BypassTransientForHint
    WA_X11DoNotAcceptFocus = PySide2.QtCore.Qt.WidgetAttribute.WA_X11DoNotAcceptFocus
    WA_X11NetWmWindowTypeCombo = PySide2.QtCore.Qt.WidgetAttribute.WA_X11NetWmWindowTypeCombo
    WA_X11NetWmWindowTypeDesktop = PySide2.QtCore.Qt.WidgetAttribute.WA_X11NetWmWindowTypeDesktop
    WA_X11NetWmWindowTypeDialog = PySide2.QtCore.Qt.WidgetAttribute.WA_X11NetWmWindowTypeDialog
    WA_X11NetWmWindowTypeDND = PySide2.QtCore.Qt.WidgetAttribute.WA_X11NetWmWindowTypeDND
    WA_X11NetWmWindowTypeDock = PySide2.QtCore.Qt.WidgetAttribute.WA_X11NetWmWindowTypeDock
    WA_X11NetWmWindowTypeDropDownMenu = PySide2.QtCore.Qt.WidgetAttribute.WA_X11NetWmWindowTypeDropDownMenu
    WA_X11NetWmWindowTypeMenu = PySide2.QtCore.Qt.WidgetAttribute.WA_X11NetWmWindowTypeMenu
    WA_X11NetWmWindowTypeNotification = PySide2.QtCore.Qt.WidgetAttribute.WA_X11NetWmWindowTypeNotification
    WA_X11NetWmWindowTypePopupMenu = PySide2.QtCore.Qt.WidgetAttribute.WA_X11NetWmWindowTypePopupMenu
    WA_X11NetWmWindowTypeSplash = PySide2.QtCore.Qt.WidgetAttribute.WA_X11NetWmWindowTypeSplash
    WA_X11NetWmWindowTypeToolBar = PySide2.QtCore.Qt.WidgetAttribute.WA_X11NetWmWindowTypeToolBar
    WA_X11NetWmWindowTypeToolTip = PySide2.QtCore.Qt.WidgetAttribute.WA_X11NetWmWindowTypeToolTip
    WA_X11NetWmWindowTypeUtility = PySide2.QtCore.Qt.WidgetAttribute.WA_X11NetWmWindowTypeUtility
    WA_X11OpenGLOverlay = PySide2.QtCore.Qt.WidgetAttribute.WA_X11OpenGLOverlay
    Wednesday = PySide2.QtCore.Qt.DayOfWeek.Wednesday
    WhatsThisCursor = PySide2.QtCore.Qt.CursorShape.WhatsThisCursor
    WhatsThisPropertyRole = PySide2.QtCore.Qt.ItemDataRole.WhatsThisPropertyRole
    WhatsThisRole = PySide2.QtCore.Qt.ItemDataRole.WhatsThisRole
    WheelFocus = PySide2.QtCore.Qt.FocusPolicy.WheelFocus
    white = PySide2.QtCore.Qt.GlobalColor.white
    WhiteSpaceMode = None # (!) real value is "<class 'PySide2.QtCore.Qt.WhiteSpaceMode'>"
    WhiteSpaceModeUndefined = PySide2.QtCore.Qt.WhiteSpaceMode.WhiteSpaceModeUndefined
    WhiteSpaceNormal = PySide2.QtCore.Qt.WhiteSpaceMode.WhiteSpaceNormal
    WhiteSpaceNoWrap = PySide2.QtCore.Qt.WhiteSpaceMode.WhiteSpaceNoWrap
    WhiteSpacePre = PySide2.QtCore.Qt.WhiteSpaceMode.WhiteSpacePre
    Widget = PySide2.QtCore.Qt.WindowType.Widget
    WidgetAttribute = None # (!) real value is "<class 'PySide2.QtCore.Qt.WidgetAttribute'>"
    WidgetShortcut = PySide2.QtCore.Qt.ShortcutContext.WidgetShortcut
    WidgetWithChildrenShortcut = PySide2.QtCore.Qt.ShortcutContext.WidgetWithChildrenShortcut
    WindingFill = PySide2.QtCore.Qt.FillRule.WindingFill
    Window = PySide2.QtCore.Qt.WindowType.Window
    WindowActive = PySide2.QtCore.Qt.WindowState.WindowActive
    WindowCloseButtonHint = PySide2.QtCore.Qt.WindowType.WindowCloseButtonHint
    WindowContextHelpButtonHint = PySide2.QtCore.Qt.WindowType.WindowContextHelpButtonHint
    WindowDoesNotAcceptFocus = PySide2.QtCore.Qt.WindowType.WindowDoesNotAcceptFocus
    WindowFlags = None # (!) real value is "<class 'PySide2.QtCore.Qt.WindowFlags'>"
    WindowFrameSection = None # (!) real value is "<class 'PySide2.QtCore.Qt.WindowFrameSection'>"
    WindowFullScreen = PySide2.QtCore.Qt.WindowState.WindowFullScreen
    WindowFullscreenButtonHint = PySide2.QtCore.Qt.WindowType.WindowFullscreenButtonHint
    WindowMaximizeButtonHint = PySide2.QtCore.Qt.WindowType.WindowMaximizeButtonHint
    WindowMaximized = PySide2.QtCore.Qt.WindowState.WindowMaximized
    WindowMinimizeButtonHint = PySide2.QtCore.Qt.WindowType.WindowMinimizeButtonHint
    WindowMinimized = PySide2.QtCore.Qt.WindowState.WindowMinimized
    WindowMinMaxButtonsHint = PySide2.QtCore.Qt.WindowType.WindowMinMaxButtonsHint
    WindowModal = PySide2.QtCore.Qt.WindowModality.WindowModal
    WindowModality = None # (!) real value is "<class 'PySide2.QtCore.Qt.WindowModality'>"
    WindowNoState = PySide2.QtCore.Qt.WindowState.WindowNoState
    WindowOverridesSystemGestures = PySide2.QtCore.Qt.WindowType.WindowOverridesSystemGestures
    WindowShadeButtonHint = PySide2.QtCore.Qt.WindowType.WindowShadeButtonHint
    WindowShortcut = PySide2.QtCore.Qt.ShortcutContext.WindowShortcut
    WindowState = None # (!) real value is "<class 'PySide2.QtCore.Qt.WindowState'>"
    WindowStates = None # (!) real value is "<class 'PySide2.QtCore.Qt.WindowStates'>"
    WindowStaysOnBottomHint = PySide2.QtCore.Qt.WindowType.WindowStaysOnBottomHint
    WindowStaysOnTopHint = PySide2.QtCore.Qt.WindowType.WindowStaysOnTopHint
    WindowSystemMenuHint = PySide2.QtCore.Qt.WindowType.WindowSystemMenuHint
    WindowTitleHint = PySide2.QtCore.Qt.WindowType.WindowTitleHint
    WindowTransparentForInput = PySide2.QtCore.Qt.WindowType.WindowTransparentForInput
    WindowType = None # (!) real value is "<class 'PySide2.QtCore.Qt.WindowType'>"
    WindowType_Mask = PySide2.QtCore.Qt.WindowType.WindowType_Mask
    X11BypassWindowManagerHint = PySide2.QtCore.Qt.WindowType.X11BypassWindowManagerHint
    XAxis = PySide2.QtCore.Qt.Axis.XAxis
    XButton1 = PySide2.QtCore.Qt.MouseButton.XButton1
    XButton2 = PySide2.QtCore.Qt.MouseButton.XButton2
    YAxis = PySide2.QtCore.Qt.Axis.YAxis
    yellow = PySide2.QtCore.Qt.GlobalColor.yellow
    ZAxis = PySide2.QtCore.Qt.Axis.ZAxis
    ZoomNativeGesture = PySide2.QtCore.Qt.NativeGestureType.ZoomNativeGesture


